### ISSUE TITLE
CMSIS RTOSv2 API: osKernelSuspend() / osKernelResume()

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS_5#101]
Can you document the use cases for these two functions?

```
/// Suspend the RTOS Kernel scheduler.
/// \return time in ticks, for how long the system can sleep or power-down.
uint32_t osKernelSuspend (void);

/// Resume the RTOS Kernel scheduler.
/// \param[in]     sleep_ticks   time in ticks for how long the system was in sleep or power-down mode.
void osKernelResume (uint32_t sleep_ticks);
```

I do not identify the functionality, if they were intended to manage power saving modes, I would say they are not very inspired.

**Comment by ReinhardKeil** [comment]
An example for using this functions is provided, take a look here http://arm-software.github.io/CMSIS_5/RTOS2/html/TickLess.html.

**Comment by ilg-ul** [comment]
again, this seems a RTX specific functionality. is it mandatory for all CMSIS RTOSv2 implementations?

to me this seems quite unfortunate and limitative, since it messes functionality from the scheduler with functionality from the ticks timer.

CMSIS++ (and POSIX in general) defines multiple timers (systick, rtc, high_res, etc), and it is possible to enter either a shallow sleep, a deep sleep or any custom sleep, based on **any** timer.

if this is a deep sleep, the application should figure out a method to compute how much time passed while sleeping, and update **all** clocks, so your RTX specific functions are not enough in the general case.

my suggestion is to keep these function RTX specific, and not make them mandatory for CMSIS RTOS.

**Comment by ReinhardKeil** [comment]
Note that the documentation has moved to: http://arm-software.github.io/CMSIS_5/RTOS2/html/theory_of_operation.html#TickLess

You are correct, this is apparently RTX specific.  We will investigate into a generic solution as we are working currently on a FreeRTOS adoption of CMSIS-RTOS v5.  See also here: https://github.com/ARM-software/CMSIS-FreeRTOS

**Comment by JonatanAntoni** [comment]
The functions are well documented here: [osKernelSuspend](https://arm-software.github.io/CMSIS_5/RTOS2/html/group__CMSIS__RTOS__KernelCtrl.html#gae26683e1606ec633354a2876c68f0c1f). Does this solve this issue?

**Comment by ReinhardKeil** [comment]
Closing as there is no further activity - initial question is resolved.
