### ISSUE TITLE
NVIC_GetEnableIRQ(IRQn_Type IRQn) function has fault in documentation

### ISSUE THREAD

**Issue by morteza120** [ARM-software/CMSIS_5#1016]
https://github.com/ARM-software/CMSIS_5/blob/cfa0772eebd14396c77c6701c93f2deb68dbda80/CMSIS/DoxyGen/Core/src/Ref_NVIC.txt#L485

The documentation for NVIC_GetEnableIRQ(IRQn_Type IRQn) function has to be like these

```
    \returns    
            - 0  Interrupt is not enabled
            - 1  Interrupt is enabled
```

but it is
```
    \returns    
            - 0  Interrupt is not enabled
            - 1  Interrupt is pending
```

**Comment by morteza120** [comment]
I add this pull request #1017

**Comment by JonatanAntoni** [comment]
Thanks for correcting this.

**Comment by morteza120** [comment]
you're welcome
