### ISSUE TITLE
CMSIS-DSP: Structure about pState in FIR

### ISSUE THREAD

**Issue by dangorogoro** [ARM-software/CMSIS_5#1023]
According to documents, the output values of FIR are calculated like this.
```c
  y[n] = b[0] * x[n] + b[1] * x[n-1] + b[2] * x[n-2] + ...+ b[numTaps-1] * x[n-numTaps+1]
```
And in the **pState**, we set old state at the front of index, and the new state at the back of index to make it easier to multiply with **pCoeffs**.
But in the documents, the state are stored in the following order.

```c
{x[n-numTaps+1], x[n-numTaps], x[n-numTaps-1], x[n-numTaps-2]....x[0], x[1], ..., x[blockSize-1]}
```

According to architecture of FIR and source code implementation, this order is wrong because there are not new state.

I think that's the order of **pState** will become following ones.
```c
{x[n-numTaps+1], x[n-numTaps], x[n-numTaps-1], x[n-numTaps-2]....x[n](==pSrc[0]), x[n+1](==pSrc[1]), ..., x[n+blockSize-1](==pSrc[blockSize-1])}
```

I've written a pull request, so please take a look at that as well. #1022

Thank you.

**Comment by christophe0606** [comment]
Thanks for helping us to improve the documentation.
