### ISSUE TITLE
CMSIS time series data example

### ISSUE THREAD

**Issue by kumarmanas** [ARM-software/CMSIS_5#1048]
Is there any plan to include time series Machine learning model in CMSIS. Or there is need of separate module for classical ML algorithim?

**Comment by christophe0606** [comment]
Hi @kumarmanas ,

We have some classical ML algorithms in the DSP folder but no time serie one.

I cannot communicate any schedule. But we consider every enhancement request.

So I have tagged this github issue as enhancement.

**Comment by christophe0606** [comment]
We have added Levinson Durbin algorithm for AR model.
More will be added in the future.
