### ISSUE TITLE
 incompatible type error when building cmsis-5.7.0 helium using gcc

### ISSUE THREAD

**Issue by shiyuanren** [ARM-software/CMSIS_5#1068]
When building cmsis-5.7 with ARM_MATH_HELIUM,  some compiler error occurred. 

1. arm_biquad_cascade_df2T_f32.c:92:19: error: incompatible type for argument 1 of '__arm_vshlcq_s32' 
include\arm_mve.h:6925:29: note: **expected 'int32x4_t' but argument is of type 'f32x4_t' {aka 'float32x4_t'}**

2. ACLE does not define implicit conversion between different data types,  but in basicmathfunctions\arm_and_u8.c:66,  cmsis source code excepts an  implicit-conversions compiler.
q7x16_t vecSrcA, vecSrcB;
**vecSrcA = vld1q(pSrcA);    //  uint8x16_t assigned to type 'q7x16_t' {aka 'int8x16_t'}**
How to solve this problem？
Thanks

**Comment by christophe0606** [comment]
@shiyuanren Unfortunately, the library has not yet been tested with the gcc including Helium support. It was not available when 5.7.0 was released.

We are working on it but I can't communicate any schedule.

In the meantime you can add typecasts where needed and in some case replacing vld1q with vld1q_f32 to make the type explicit if the compiler can't infer it.

**Comment by christophe0606** [comment]
@shiyuanren  You cna also try to add the option  -flax-vector-conversions when compiling
