### ISSUE TITLE
RTOS2 tickless mode IRQ priority question

### ISSUE THREAD

**Issue by tobermory** [ARM-software/CMSIS_5#1134]
I have successfully tested an RTX5 application where I can achieve tickless mode via the idlerThread.  I call t=osKernelSuspend and osKernelResume, and between them I enable my MCU's low-power RTC peripheral to count t. I then go into deep sleep.  The RTC's interrupt awakes the CPU.

My question is: does that RTC interrupt have to have a certain priority?  Is my RTC now considered 'part of the RTOS' ?

I know that if the RTC is used as a substitute for SysTick, via user-pluggable os_tick api, it would need lowest IRQ priority (0xff, my MCU has 3 priority bits so that equates to 7), but is this needed for tickless too?  I note that RTX builds for my MCU with SVC at priority 6 and SysTick and PendSV at 7.

**Comment by RobertRostohar** [comment]
>  Is my RTC now considered 'part of the RTOS' ?

No. When RTOS Kernel is suspended with osKernelSuspend the OS Tick is stopped and RTOS waits for osKernelResume. External timer (ex: RTC) which is used to wake-up the device from low power is completely independent from RTOS.

> does that RTC interrupt have to have a certain priority? 

Not for wake-up from low power mode. Usually any enabled interrupt will wake-up the device when interrupt is activated. There is no requirement on the wake-up timer priority from RTOS perspective.

When such timer is used as the OS Tick timer (substitute for SysTick) then its priority needs to be the lowest as already mentioned.
