### ISSUE TITLE
Conflicting declaration and implementation of function arm_clip_f32

### ISSUE THREAD

**Issue by PolarPangda** [ARM-software/CMSIS_5#1140]
In /DSP/DSP_Lib_TestSuite/Common/inc/math_helper.h, it's declared as
void arm_clip_f32(float *pIn, uint32_t numSamples);

In /DSP/Include/dsp/basic_math_functions.h, it's declared as 
void arm_clip_f32(const float32_t * pSrc, float32_t * pDst, float32_t low, float32_t high, uint32_t numSample).

**Comment by christophe0606** [comment]
@PolarPangda  The DSP_Lib_TestSuite is deprecated. We no more use it to test.

But, I have just realized that the `void arm_clip_f32(float *pIn, uint32_t numSamples);` is also defined in the Examples although it is not used.

So, I have just made a commit to correct this and remove this function.

Thanks for reporting the problem.
