### ISSUE TITLE
missing arm_sqrt_f32 from DSP?

### ISSUE THREAD

**Issue by Niklas-Zeidler** [ARM-software/CMSIS_5#1146]
In the reference [link](https://arm-software.github.io/CMSIS_5/DSP/html/group__SQRT.html#ga5f37f479666ee8ff9711b334286c60ed) a function called "arm_sqrt_f32" is mentioned. "arm_std_f32" is also referencing it. But it is nowhere to be found in the source code.

**Comment by christophe0606** [comment]
@Niklas-Zeidler  It is defined as an inline function in the header file dsp/fast_math_functions.h

You also get it by just including arm_math.h
