### ISSUE TITLE
compiling for host (MacOS) gives compilation error in SupportFunctions/arm_q7_to_q31.c

### ISSUE THREAD

**Issue by sigurdpl** [ARM-software/CMSIS_5#1149]
I followed the advice in #1015 for compiling on MacOS.

I am now getting this error:
/CMSIS_5-5.7.0/CMSIS/DSP/Source/SupportFunctions/arm_q7_to_q31.c:120:16: error: implicit declaration of function '__ROR' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    *pDst++ = (__ROR(in, 8)) & 0xFF000000;

cmake --build ../CMSIS_5-5.7.0/cmsis_test/cmake-build-debug --target testcmsisdsp -- -j 6

**Comment by sigurdpl** [comment]
Update, i tried the Development branch. It compiles. The problem one was the 5.7.0 release

**Comment by sigurdpl** [comment]
Only problem now is the SET(CMAKE_C_FLAGS_DEBUG "-D_DEBUG -D__GNUC_PYTHON__"  CACHE INTERNAL "") seems to disable debugger

**Comment by christophe0606** [comment]
@sigurdpl I don't think I am touching the CMAKE_C_FLAGS when building for host. 
What's inside your cmake-build-debug ?

**Comment by christophe0606** [comment]
@sigurdpl Note that there is a new option. You no more need to set the CMAKE_C_FLAGS to force __GNUC_PYTHON__  

You can just use -DHOST=ON as a cmake option for the CMSIS-DSP.

**Comment by sigurdpl** [comment]
Hi, thanks for the reply. I will definitely try that. This worked though: SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -D__GNUC_PYTHON__"  CACHE INTERNAL "")

**Comment by sigurdpl** [comment]
But will definitely try with the -DHOST=ON option instead

**Comment by sigurdpl** [comment]
Removed completely the SET(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -D__GNUC_PYTHON__" CACHE INTERNAL "")
Set -DHOST=ON

That totally worked!
