### ISSUE TITLE
Typo in CMSIS-DSP reference

### ISSUE THREAD

**Issue by yjy19999** [ARM-software/CMSIS_5#1156]
![image](https://user-images.githubusercontent.com/20664115/111854809-38ed3b80-895c-11eb-8a1e-416026d65baa.png)

**Comment by christophe0606** [comment]
@yjy19999 Thank you. I'll correct it.

**Comment by christophe0606** [comment]
Corrected in https://github.com/ARM-software/CMSIS_5/issues/1156
