### ISSUE TITLE
All partial convolution functions effectively getting stuck if firstIndex >srcBLen -1

### ISSUE THREAD

**Issue by kikakeule** [ARM-software/CMSIS_5#1165]
When choosing a start index that is greater then the length of source B, the function gets stuck in block 1.

For example consider arm_conv_partial_f32.c:

Commit #4146c13 changed the type of blockSize1, blockSize2 and blockSize3 to unsigned without adapting the logic:

`blockSize1 = ((int32_t) srcBLen - 1) - (int32_t) firstIndex;`
`blockSize1 = (blockSize1 > 0) ? ((check > (srcBLen - 1U)) ? blockSize1 : numPoints) : 0`

(and, respecitvely, the logic of blocksize2)

Hence, if firstIndex  is larger than srcBLen - 1, blocksize1 wraps around instead of being catched by the second line and set to 0. this effectively leads to the function hanging.

**Comment by christophe0606** [comment]
@kikakeule Thanks for reporting this bug (and the other one). I am going to look at this.

**Comment by christophe0606** [comment]
Should be corrected in commit https://github.com/ARM-software/CMSIS_5/commit/976878a3576dd9fa1f33cd6ad3064a8b692f81e7
