### ISSUE TITLE
All partial convolution functions calculate wrong if firstIndex > srcALen

### ISSUE THREAD

**Issue by kikakeule** [ARM-software/CMSIS_5#1167]
The first src pointer of stage 3 is not correctly initialized:
Currently, the pointer is always set to:
`pSrc1 = (pIn1 + srcALen) - (srcBLen - 1U);`

This results in the exact same values for every firstIndex that >= srcALen (besides the values being place with an offset in the destination array)

Instead, the function needs to catch the case where the first index is larger than srcALen like so:
`if (firstIndex > srcALen)`
`    pSrc1 = (pIn1 + firstIndex) - (srcBLen - 1U);`
`else`
`    pSrc1 = (pIn1 + srcALen) - (srcBLen - 1U);`

**Comment by christophe0606** [comment]
Should be corrected in commit https://github.com/ARM-software/CMSIS_5/commit/bb8c3eb6d4c2a063d4caf0cfd99badb1c7e660f1
