### ISSUE TITLE
RTOS2 special library for Infineon XMC4000 required?

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#117]
In RTOS1 special versions for Infineon XMC4000 are included as libraries. Can RTOS2 used by XMC4000 with standard library?

**Comment by jkrech** [comment]
This special version was necessary to deal with a specific behavior of the initial silicon revision for this device series. We have been told that subsequent revisions do not require this special handling anymore. Therefore we decided not to introduce a special library for RTOS2. It is best to contact the silicon vendor to find out how to identify devices that do or do not require special handling.

**Comment by JonatanAntoni** [comment]
Is this issue solved? So I would ask you to close this issue, please.
