### ISSUE TITLE
arm_levinson_durbin_q31.c compile warinig

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS_5#1188]
Can anybody add fix for unused variable in function divide - like on my screenshot.
![image](https://user-images.githubusercontent.com/34999007/116792320-8ff03f80-aac8-11eb-8c68-8810f97b5cf4.png)

**Comment by christophe0606** [comment]
@ua1arn I am going to clean this one and a few other compilation warnings.

**Comment by christophe0606** [comment]
@ua1arn It should be corrected in latest commit https://github.com/ARM-software/CMSIS_5/commit/8c6e37817c3a0547a4bfdc6aaf16c2233fa9192b
