### ISSUE TITLE
SVD documentation: `<series>` minOccurs 

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS_5#119]
The documentation page for the `device` element (http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_device.html) lists the `series` child element as `1..1` while the schema file lists it as `minOccurs="0"`.

Suggestion:

- update the documentation page to match the schema file

**Comment by bn01Mra** [comment]
- updated elenet 'series' to 1.

I'll submit the corrections for SVD at the end of the day; please wait until then for verification.
