### ISSUE TITLE
SVDConv version 3.2.17 does not parse the alternatePeripheral tag properly.

### ISSUE THREAD

**Issue by David-Garcia-Polo** [ARM-software/CMSIS_5#12]
If an SVD file has two peripherals, the second one marked with the tag <alternatePeripheral>, the SVDConv.exe v3.2.17 generates a warning M352 and returns 1 (instead of Success 0).

This is in contradiction of the specified usage of the tag. From the documentation in CMSIS 4.5.0:
"All address blocks in the memory space of a device are assigned to a unique peripheral by default. If there are multiple peripherals describing the same address blocks, this needs to be specified explicitly. A peripheral redefining an address block needs to specify the name of the peripheral that is listed first in the description. If no alternate peripheral is specified, then the SVDConv utility will generate errors."

Please see attached SVD files for example. Rename to .svd since Github does not support .svd extension.

[M352_warning.svd.txt](https://github.com/ARM-software/CMSIS_5/files/165315/M352_warning.svd.txt)
[M352_no_warning.svd.txt](https://github.com/ARM-software/CMSIS_5/files/165316/M352_no_warning.svd.txt)

**Comment by thorstendb-ARM** [comment]
fixed in SVDConv V3.2.25
