### ISSUE TITLE
SVD Documentation: `<addressBlock>` element & other mismatches

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS_5#120]
The documentation page for the `addressBlock` element (http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_peripherals.html#elem_addressBlock) 
lists `addressBlock` as child of `addressBlock`, while the schema does not.

Suggestion:

- update the documentation and remove the recursive definition

**Comment by ilg-ul** [comment]
The documentation for register/fields (http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_fields) reads `1..1` occurrences for `<field>`; probably it should read `1..*`.

**Comment by ilg-ul** [comment]
The documentation for fields/field (http://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_field) reads `0..2` occurrences for `<enumeratedValues>`; probably it should read `0..*`,

**Comment by jkrech** [comment]
The `<enumeratedValues>` tag is intentionally limited to a maximum of two instances.
This has to do with the tag `<usage>...</usage>`.  The usage can be either 
- read
- write
- read-write
You either have a single description used for read and write or two individual descriptions with the usage read and the other with the usage write.

**Comment by bn01Mra** [comment]
- removed recursive element 'addressBlock' from 'addressBlock'.
- set occurrence of element 'field' in element 'fields' to [1..*]

I"ll update the documentation issues and submit the pages at the end of the day. Please wait until then.
