### ISSUE TITLE
int_width parameter in arm_nn_activations_direct_q7

### ISSUE THREAD

**Issue by MiguelCosta94** [ARM-software/CMSIS_5#1220]
Hi,

I am facing some difficulties to understand the parameter int_widtth in arm_nn_activations_direct_q7 function. Is this parameter supposed to be the int-width of the input data or the int-width of the data returned by arm_nn_activations_direct_q7 ?

Best regards,
Miguel

**Comment by felix-johnny** [comment]
@MiguelCosta94 Thanks for the question. int-width here is the int width of the input. 
 The function that you are looking at is part of the legacy functions(https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis) which has minimal support.
 
   The *_s8 functions are the actively maintained ones and can be run from TFLM (https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/kernels/cmsis_nn) . If you have any questions on that, please let me know!
