### ISSUE TITLE
CMSIS-NN with FP32 implementations

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/CMSIS_5#1228]
Hi,

I have seen that all the CMSIS-NN layers have S8, Q7, Q15 implementations. Are there FP32 implementations? If not, are there any plans to add them in near future.

Thanks,
Praveen.

**Comment by felix-johnny** [comment]
@uu-praveeng The focus for CMSIS-NN is on s8 and s16(new). For Cortex-M processors, I don't think there will be any F32 implementations in the future.
