### ISSUE TITLE
ARM_MATH_DSP is not behind a define guard in arm_conv_partial_q7.c

### ISSUE THREAD

**Issue by jgoldstn** [ARM-software/CMSIS_5#1248]
It appears throughout most of the DSP codebase `ARM_MATH_DSP` is checked by checking if the value is defined. This is not the case in `arm_conv_partial_q7.c`. In this case, it will cause compiler warnings if checks for undefined preprocessor tokens are enabled `-Werror,-Wundef`.

https://github.com/ARM-software/CMSIS_5/blob/ee79c2197e6529f5274893e3764d0ded04aff22e/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c#L67

**Comment by christophe0606** [comment]
@jgoldstn Thanks for reporting it. I'll correct this.

**Comment by christophe0606** [comment]
Should be corrected in commit https://github.com/ARM-software/CMSIS_5/commit/a0ba1d775d8cb579c7b3018d08d0b1da354e0d04
