### ISSUE TITLE
Mutex documentation is misleading 

### ISSUE THREAD

**Issue by bulislaw** [ARM-software/CMSIS_5#125]
Documentation says `The advantage of a mutex is that it introduces thread ownership. When a thread acquires a mutex and becomes its owner, subsequent mutex acquires from that thread will succeed immediately without any latency. Thus, mutex acquires/releases can be nested.`

But acquiring mutex from a thread twice results in a hang (or timeout). To actually enable what the docs are saying you need to set `.attr_bits = osMutexRecursive`, the high level documentation should mention that.

**Comment by JonatanAntoni** [comment]
The documentation was updated in the meanwhile. It states 
> When a thread acquires a mutex and becomes its owner, subsequent mutex acquires from that thread will succeed immediately without any latency (if osMutexRecursive is specified). Thus, mutex acquires/releases can be nested.
Is this clear enough now? Please close this issue if you do not have any further questions.

**Comment by bulislaw** [comment]
Thanks, I think it's clear now. Closing.
