### ISSUE TITLE
quant_params for convolution

### ISSUE THREAD

**Issue by uu-praveeng** [ARM-software/CMSIS_5#1259]
Hi,

Is there a documented way on how to calculate the multiplier and shift of the _cmsis_nn_per_channel_quant_params_ (regarding convolve_s8 input)? or Do we have to calculate it similar to _tflite::PopulateConvolutionQuantizationParams_? Are there any plans to merge these calculations into the cmsisnn_conv_s8 function in the future?

Is it expected that size of quant_params is the same as output channels? 
To be more specific if output channels of convolving is 8. Do I need to fill quant_params with 8 multipliers,8 shifts? 
Are there any plans to add an alternate version of s8 where only a single multiplier and shift could be passed?

Thanks,
Praveen.

**Comment by felix-johnny** [comment]
@uu-praveeng  Sorry for the delay.. The quantization parameters are to be calculated as per TFLM spec.So, what you say, sounds right.
_Is it expected that size of quant_params is the same as output channels?_ : Yes, as we follow per channel quantization.

 _To be more specific if output channels of convolving is 8. Do I need to fill quant_params with 8 multipliers,8 shifts? :_ That is correct.

 _Are there any plans to add an alternate version of s8 where only a single multiplier and shift could be passed? :_  So,  a special case where it is to be treated as a per-tensor quantization. I am afraid it is not on the cards now, but I can get back with an analysis on what it means..

 I'll close this ticket for now..
