### ISSUE TITLE
DSP_Lib_TestSuite

### ISSUE THREAD

**Issue by killua-killua** [ARM-software/CMSIS_5#1260]
Here is a question for the CMSIS_5.8.0 released packet.
Why does it not contain 'DSP_Lib_TestSuite' folder anymore ?

**Comment by christophe0606** [comment]
@killua-killua It was replaced by a more extensive testing framework in folder DSP/Testing

DSP_Lib_TestSuite was no more maintained and its coverage was not good enough.

The new framework is relying on test patterns generated from numpy/scipy.
