### ISSUE TITLE
Multiple definition in CMSIS DSP v1.8.0. library 

### ISSUE THREAD

**Issue by ShailajaPG** [ARM-software/CMSIS_5#1272]
'Multiple definition' errors occurs when using functions from the CMSIS-DSP v1.8.0 library are used.

CMSIS-DSP library contains source codes in 13 individual folders and each folder contains a particular '.c' file. The .c file has a list of '#includes'. These '#includes', insert all the source codes present in the current directory which leads the src files in the current directory to be compiled twice.

**Comment by JonatanAntoni** [comment]
Hi @ShailajaPG,

Thanks for getting in touch. These particular C files can be used to speed up compilation when one wants to include the full DSP library. The alternative is to add only specific function C files as needed. As you pointed out, one must not add both to a project at the same time.

Using an RTE-enabled environment, the correct files are selected automatically based on the information given in the PDSC file. In self managed projects one need to take care about the file selection manually.

Cheers,
Jonatan
