### ISSUE TITLE
CMSIS SVD validation failed for Cortex-M33 

### ISSUE THREAD

**Issue by radhika-raghavendran** [ARM-software/CMSIS_5#1288]
When running the schema validator in \CMSIS\Utilities\CMSIS-SVD.xsd against the SVD file for our microcontroller, we find some errors. According to the documentation in https://arm-software.github.io/CMSIS_5/SVD/html/elem_registers.html#elem_register and https://arm-software.github.io/CMSIS_5/SVD/html/elem_peripherals.html#elem_peripheral it is allowed in the SVD.
Can you check if the schema file requires an update?

Attached are the errors in the SVD file which running the schema validation tool.
![Register_description2](https://user-images.githubusercontent.com/9882004/130037022-4313a3cb-c510-4503-8292-921c325f46f1.JPG)
![Register_description](https://user-images.githubusercontent.com/9882004/130037107-c6874e0d-da15-423d-903f-79165cde4c5f.JPG)
![Peripheral_headerstructure2](https://user-images.githubusercontent.com/9882004/130037116-d8d253b3-2484-45d4-8f8b-381a9623cb81.JPG)
![Peripheral_headerstructure](https://user-images.githubusercontent.com/9882004/130037127-8e3bed83-fadb-445c-a27a-dddecadd98ba.JPG)

**Comment by JonatanAntoni** [comment]
Hi @radhika-raghavendran,

Looking into the schema definition turns out that all these elements are declared to be in a sequence, i.e. need to be in order. Please try to arrange the elements according to the order in the schema and check again. I expect this to work.

I am going to clarify if there is a (technical) requirement for this restriction.

Cheers,
Jonatan

**Comment by radhika-raghavendran** [comment]
Thank you for the clarification. However there is still an issue with the validation with schema given in the ARM_CMSIS distribution.
According to the specifications, there is no requirement to include a description in the cluster element, as shown below.
![image](https://user-images.githubusercontent.com/9882004/133086119-fac435cd-1e59-458a-8888-496d88b6107d.png)
I get a validation error when I do not include the description tag in the cluster element, as shown here:
![image](https://user-images.githubusercontent.com/9882004/133086285-30a08cc7-a785-4d0a-a9a9-001e85189b66.png)
When I include the description tag, with no other changes, the validation is complete and successful as shown here.
![image](https://user-images.githubusercontent.com/9882004/133086493-3864ac45-1040-40ac-bca2-ba56617dec85.png)

**Comment by JonatanAntoni** [comment]
Hi @radhika-raghavendran,

yes, you are right. We need to clarify the documentation.
The current schema mandates a description in this case.

Cheers,
Jonatan

**Comment by radhika-raghavendran** [comment]
The schema validation is now complete. Please add required sections and make modifications to your documentation.
I will close this ticket.

**Comment by radhika-raghavendran** [comment]
Closed ticket. Documentation for SVD file to be modified by the ARM team.
