### ISSUE TITLE
DSP: SNR test disabled in test_fir_interpolate_f32

### ISSUE THREAD

**Issue by stephanosio** [ARM-software/CMSIS_5#1289]
`ASSERT_SNR` is not being called in `test_fir_interpolate_f32` (commented out):
https://github.com/ARM-software/CMSIS_5/blob/13b9f72f212688d2306d0d085d87cbb4bf9e5d3f/CMSIS/DSP/Testing/Source/Tests/DECIMF32.cpp#L121

Was this intentional? If so, why?

**Comment by christophe0606** [comment]
Corrected in 4f7f38fe154c09d53e067c42cb268305f0c2aaeb

It was a mistake. I have reenabled the SNR test.

**Comment by stephanosio** [comment]
> It was a mistake. I have reenabled the SNR test.

Thanks for clarifying. Closing as this issue has been resolved.
