### ISSUE TITLE
which compiler to use?

### ISSUE THREAD

**Issue by lyxcliang** [ARM-software/CMSIS_5#1297]
About CMAKE_PREFIX_PATH at /CMSIS/DSP/README.md，the note is “path to compiler(folder containing the bin folder)”, what is the compiler refer to ? The Cmake or ARMCC?

**Comment by christophe0606** [comment]
@lyxcliang It depends which toolchain file you are using with your cmake.
If you are using armac6.cmake from DSP folder then you need to use armclang.
