### ISSUE TITLE
SVDConv version 3.2.17 does not like 0xFFFFFFFF in <enumeratedValue>

### ISSUE THREAD

**Issue by David-Garcia-Polo** [ARM-software/CMSIS_5#13]
If an SVD file defines a register with a field of 32 bits and one of the <enumeratedValue> has <value> 0xFFFFFFFF (perfectly valid 32-bit number, and quite popular), SVDConv fails with error M369. The very similar 0xFFFFFFFE does not fail. also return value from the program is 2, instead of success (0).

Please see attached SVD files for example. Rename to .svd since Github does not support .svd extension.

[M369_error.svd.txt](https://github.com/ARM-software/CMSIS_5/files/165391/M369_error.svd.txt)
[M369_no_error.svd.txt](https://github.com/ARM-software/CMSIS_5/files/165392/M369_no_error.svd.txt)

**Comment by thorstendb-ARM** [comment]
fixed in SVDConv V3.2.25

**Comment by ReinhardKeil** [comment]
David, the new version is available here:
https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/Utilities

Do you have a chance to test/review the new version and close the related issues?

**Comment by David-Garcia-Polo** [comment]
yes. will test today.

**Comment by ReinhardKeil** [comment]
Closed now as there is no further activity
