### ISSUE TITLE
The Input buffer from arm_vsqrt isn't const

### ISSUE THREAD

**Issue by jbr-smtg** [ARM-software/CMSIS_5#1304]
Hello :)

Input buffers in the fast math functions of CMSIS-DSP are mostly **const**, and this particular set of methods "arm_vsqrt" don't take a **const** input buffer.
This looks like something was forgotten here.

Thanks again!

**Comment by christophe0606** [comment]
@jbr-smtg You're right. I'll correct it.

**Comment by christophe0606** [comment]
Corrected in commit 285816e38ec8cc3289acefc1786a28726be0929d

**Comment by jbr-smtg** [comment]
Perfect 👍
