### ISSUE TITLE
DSP: Plenty of sign issues with unsigned variables and arrays

### ISSUE THREAD

**Issue by TTornblom** [ARM-software/CMSIS_5#1328]
While compiling some of the DSP examples with the IAR compiler, for Cortex-M55, there are lots of warnings about assigning negative values to unsigned variables.

Example:
[141/541] Building C object bin_dsp\FilteringFunctions\CMakeFiles\CMSISDSPFiltering.dir\arm_levinson_durbin_f32.c.o

        static uint32_t orgOffsetArray[4]={0,1,-1,-2};
                                                  ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f32.c",132  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint32_t offsetIncArray[4]={2,2,-2,-2};
                                                     ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f32.c",133  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint32_t offsetIncArray[4]={2,2,-2,-2};
                                                        ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f32.c",133  Warning[Pe068]: 
          integer conversion resulted in a change of sign
[142/541] Building C object bin_dsp\FilteringFunctions\CMakeFiles\CMSISDSPFiltering.dir\arm_levinson_durbin_q31.c.o

        static uint32_t orgOffsetArray[4]={0,1,-1,-2};
                                                  ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_q31.c",199  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint32_t offsetIncArray[4]={2,2,-2,-2};
                                                     ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_q31.c",200  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint32_t offsetIncArray[4]={2,2,-2,-2};
                                                        ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_q31.c",200  Warning[Pe068]: 
          integer conversion resulted in a change of sign

[147/541] Building C object bin_dsp\FilteringFunctions\CMakeFiles\CMSISDSPFiltering.dir\arm_levinson_durbin_f16.c.o

        static uint16_t orgOffsetArray[8]={0,1,2,3,-1,-2,-3,-4};
                                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",132  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static uint16_t orgOffsetArray[8]={0,1,2,3,-1,-2,-3,-4};
                                                         ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",132  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static uint16_t orgOffsetArray[8]={0,1,2,3,-1,-2,-3,-4};
                                                            ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",132  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint16_t offsetIncArray[8]={4,4,4,4,-4,-4,-4,-4};
                                                         ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",133  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint16_t offsetIncArray[8]={4,4,4,4,-4,-4,-4,-4};
                                                            ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",133  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint16_t offsetIncArray[8]={4,4,4,4,-4,-4,-4,-4};
                                                               ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\FilteringFunctions\arm_levinson_durbin_f16.c",133  Warning[Pe068]: 
          integer conversion resulted in a change of sign

        static const uint16_t offsetIncArray[8]={4,4,4,4,-4,-4,-4,-4};

[431/541] Building C object bin_dsp\TransformFunctions\CMakeFiles\CMSISDSPTransform.dir\arm_cfft_f32.c.o

          (0 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",102  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (1 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",103  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",104  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (9 - 16) * sizeof(q31_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",105  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",311  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (1 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",312  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",313  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (9 - 16) * sizeof(q31_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f32.c",314  Warning[Pe068]: 
          integer conversion resulted in a change of sign                  
                                                ^

[436/541] Building C object bin_dsp\TransformFunctions\CMakeFiles\CMSISDSPTransform.dir\arm_cfft_f16.c.o

         {(0 - 16) * sizeof(float16_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",101  Warning[Pe068]: 
          integer conversion resulted in a change of sign

         , (4 - 16) * sizeof(float16_t *)
           ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",102  Warning[Pe068]: 
          integer conversion resulted in a change of sign

         , (8 - 16) * sizeof(float16_t *)
           ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",103  Warning[Pe068]: 
          integer conversion resulted in a change of sign

         , (12 - 16) * sizeof(float16_t *)};
           ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",104  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",309  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (4 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",310  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_f16.c",311  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (12 - 16) * sizeof(q31_t *)

[442/541] Building C object bin_dsp\TransformFunctions\CMakeFiles\CMSISDSPTransform.dir\arm_cfft_q15.c.o

          (0 - 16) * sizeof(q15_t *), (4 - 16) * sizeof(q15_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",50  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q15_t *), (4 - 16) * sizeof(q15_t *),
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",50  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q15_t *), (12 - 16) * sizeof(q15_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",51  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q15_t *), (12 - 16) * sizeof(q15_t *)
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",51  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q15_t *), (4 - 16) * sizeof(q15_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",285  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q15_t *), (4 - 16) * sizeof(q15_t *),
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",285  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q15_t *), (12 - 16) * sizeof(q15_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q15.c",286  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q15_t *), (12 - 16) * sizeof(q15_t *)
                                      ^

[452/541] Building C object bin_dsp\TransformFunctions\CMakeFiles\CMSISDSPTransform.dir\arm_cfft_q31.c.o

          (0 - 16) * sizeof(q31_t *), (1 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",52  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q31_t *), (1 - 16) * sizeof(q31_t *),
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",52  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *), (9 - 16) * sizeof(q31_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",53  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *), (9 - 16) * sizeof(q31_t *)
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",53  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q31_t *), (1 - 16) * sizeof(q31_t *),
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",302  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (0 - 16) * sizeof(q31_t *), (1 - 16) * sizeof(q31_t *),
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",302  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *), (9 - 16) * sizeof(q31_t *)
          ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",303  Warning[Pe068]: 
          integer conversion resulted in a change of sign

          (8 - 16) * sizeof(q31_t *), (9 - 16) * sizeof(q31_t *)
                                      ^
"C:\Users\thomasto\Projects\CMSIS_5\CMSIS\DSP\Source\TransformFunctions\arm_cfft_q31.c",303  Warning[Pe068]: 
          integer conversion resulted in a change of sign

**Comment by christophe0606** [comment]
@TTornblom Depending on the level of warning and the compiler there can be a **lot** of warnings and a lot in the legacy code.
So, I won't be able to correct all of those issues. It would take too much time. 

But, I'll look at your shorter list and see what can be corrected. I know that for some of the offset ones, it was done on purpose so it is not an error. But some explicit casts may be required,

**Comment by christophe0606** [comment]
@TTornblom Can you tell me if for:

`static uint32_t orgOffsetArray[4]={0,1,-1,-2};
`

Rewriting as

`static uint32_t orgOffsetArray[4]={0,1,(uint32_t )-1,(uint32_t )-2};
`

is solving the issue ?

Because before making all of the changes, I want to be sure it will solve the issue with your compiler.

I can't enable the -Wsign-conversion because then I'll get too many warnings related to intrinsics like CLZ, etc ...

I don't have a warning option which would (like it look to be the case on your side), enable those warning only  for a more restricted set of cases.

**Comment by TTornblom** [comment]
Yes, this seems to work.

**Comment by christophe0606** [comment]
@TTornblom I have just pushed commit https://github.com/ARM-software/CMSIS_5/commit/520994cb3deaac8fd151ca75cb75d3945172dcfb

Is it solving the issue ?

**Comment by TTornblom** [comment]
Yes, it solves the arm_levinson_durbin* issues, the other issues can be solved by casting the "sizeof" operators in arm_cfft_*.c to an int32_t.

**Comment by christophe0606** [comment]
Ah ok. So it is not issue I fixed. I changed the type of the array because the values are negatives. 

` (8 - 16) * sizeof(q31_t *), (9 - 16) * sizeof(q31_t *)`

But I have not casted the output of sizeof in this case.

I'll do it.

**Comment by TTornblom** [comment]
I can fix this, if you want

**Comment by christophe0606** [comment]
@TTornblom I have pushed https://github.com/ARM-software/CMSIS_5/commit/15a1b2825ed867a13cf2036d27cd8b8167cec859

I hope it is solving the issue.

I have seen your other pull request but it is much more than this issue : there is also IAR support for the test framework.

I'd be happy to add this to the test framework. But let's keep both issues separate.
