### ISSUE TITLE
IAR compiler build error on DSP F16 files

### ISSUE THREAD

**Issue by noah-kiser-rea** [ARM-software/CMSIS_5#1340]
We see the following error message when building this file sing the IAR 9.10.2 compiler:

"/CMSIS_5/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c",117  Error[Pe020]: identifier "__FLT16_MAX__" is undefined

Our compiler command line is:

iccarm /CMSIS_5/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c /CMSIS_5/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o --no_wrap_diagnostics -
/*includes*/ -e --cpu Cortex-M4 --fpu VFPv4_sp --debug --dlib_config
normal --endian little --cpu_mode thumb -Oh

**Comment by christophe0606** [comment]
I am closing the issue. Feel free to reopen if you have more information or if the problem was not solved.

I know f16 code can be built with IAR compiler (at least with the develop branch).
