### ISSUE TITLE
CMSIS-DSP: Add vector multiply-accumulate

### ISSUE THREAD

**Issue by jferreir** [ARM-software/CMSIS_5#1343]
Add functions to CMSIS DSP similar to the ones found in https://projectne10.github.io/Ne10/doc/group__MLA__VEC.html

**Comment by christophe0606** [comment]
We are moving CMSIS-DSP to a new repository : https://github.com/ARM-software/CMSIS-DSP

I have recreated the github issues on the new repository (sometimes merging a few related ones). You can see the link just above this comment (... mentioned this issue ...).

So, I am closing the github issue here.
