### ISSUE TITLE
What are the dimensions of the concatenation function?

### ISSUE THREAD

**Issue by jiaodawuyanzu** [ARM-software/CMSIS_5#1418]
What is the dimension of the input tensor in the arm_concatenation_s8_x function? Is it the same as the dimension [N H W C] of the input input in the convolution?

**Comment by felix-johnny** [comment]
Thanks for the question @jiaodawuyanzu . I've provided an answer in your earlier question https://github.com/ARM-software/CMSIS_5/discussions/1416 instead.

**Comment by jiaodawuyanzu** [comment]
Thanks your answer
