### ISSUE TITLE
CMSIS-DSP PythonWrapper

### ISSUE THREAD

**Issue by christophe0606** [ARM-software/CMSIS_5#1428]
The wrapper is now available as a standard Python package:

https://pypi.org/project/cmsisdsp/1.2.1/

`pip install cmsisdsp`

It is a source package so a compiler is still needed.

I have tested the build on Linux, Windows and Mac.

But I can't test all combinations of OS/Compilers.

Nevertheless it should be easier to install the wrapper than it was before.

**Comment by xudonglei** [comment]
The PythonWrapper  is very useful to me.  But I can not find function arm_vlog_f32 in the Wrapper. It is strange. I use cmsis_5_5.8.0

**Comment by christophe0606** [comment]
Now documented in the README on the new CMSIS-DSP repository:

https://github.com/ARM-software/CMSIS-DSP
