### ISSUE TITLE
Core_A : cmsis_gcc.h : The __RBIT defines are wrongly referring to Cortex-M

### ISSUE THREAD

**Issue by vanvught** [ARM-software/CMSIS_5#1445]
See https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/Core_A/Include/cmsis_gcc.h#L463
The `__RBIT` defines are wrongly referring to Cortex-M

**Comment by GuentherMartin** [comment]
Hello @vanvught, thank you for pointing out.
Please verify the fix. As far I can see is the `rbit` instruction available for all Cortex-A cores.

**Comment by vanvught** [comment]
Thank you @GuentherMartin, this fix is working fine.
