### ISSUE TITLE
arm_biquad_cascade_df1_q15 BUG！！！

### ISSUE THREAD

**Issue by jiaodawuyanzu** [ARM-software/CMSIS_5#1449]
arm_biquad_cascade_df1_q15 The C and ARM_MATH_MVEI implementation code results of this function are inconsistent. Is the implementation of ARM_MATH_MVEI wrong?

**Comment by christophe0606** [comment]
@jiaodawuyanzu The two functions should behave the same.
Do you have an example where they give a different result ?

**Comment by christophe0606** [comment]
Fell free to reopen if you have more information.
