### ISSUE TITLE
can not use arm_vlog_f32  in python wrapper

### ISSUE THREAD

**Issue by xudonglei** [ARM-software/CMSIS_5#1465]
I can use pythonwrapper for cmsis dsp now(cmsis_5_5.8.0).  But I can not use arm_vlog_f32 function,  this function is not in python wrapper.  It is strange.

**Comment by christophe0606** [comment]
@xudonglei I have just checked and it is available in the version on pypi:
`pip install cmsisdsp`

This version is providing more functions from CMSIS-DSP than older versions.

**Comment by xudonglei** [comment]
It works,  thank you!
