### ISSUE TITLE
Segmentation fault when description field > +-570 characters

### ISSUE THREAD

**Issue by JakkoVerhallen** [ARM-software/CMSIS_5#147]
Hi,

I'm experiencing segmentation faults when the description of a register field is too long.
It should be quite easy to reproduce.

I'm using SVDConv 4.4.4 on Linux RH6.

Thanks!
Jakko

**Comment by JonatanAntoni** [comment]
@JakkoVerhallen may I ask you to review the latest version of SVDConv for Linux and close this issue? Thx.

**Comment by JakkoVerhallen** [comment]
Hi Jonatan,

Thanks for your email.
I have checked the latest version, and I don’t need to remove long descriptions anymore, so it seems to be fixed!

Is there any other action I should take? I’m quite new to github.


Thanks!
Jakko

**Comment by thorstendb-ARM** [comment]
Hi,

the Seg.Fault should be fixed in SVDConv Linux v3.3.3
