### ISSUE TITLE
Support for N>1 in maxpool CMSIS-NN implementation

### ISSUE THREAD

**Issue by asparkhi** [ARM-software/CMSIS_5#1483]
One of the users of TVM via CMSIS-NN sought support of N>1 in maxpool. Here is the link: https://discuss.tvm.apache.org/t/cmsis-nn-qnn-max-pool2d-layout-on-cortex-m7-without-npu/12712/3. @felix-johnny

**Comment by felix-johnny** [comment]
@ashutosh-arm Is this still relevant? If so, could you move this to the new repository?

**Comment by JonatanAntoni** [comment]
New location: [https://github.com/ARM-software/CMSIS-NN](https://github.com/ARM-software/CMSIS-NN)

**Comment by asparkhi** [comment]
I have moved it there. Thanks!
