### ISSUE TITLE
Relative Path Not found ERROR M204

### ISSUE THREAD

**Issue by enversultanov** [ARM-software/CMSIS_5#1501]
Hi!

I have exported uvision project to .cprj format and trying to use cbuild.sh for building it.
The command I use looks like this:
`cbuild.sh MyProj.cprj --cmake` and the result is:
```
*** ERROR M204:
  Path not found: 'C:/Repos/repo_name/Module/Project/"../Module Name/include"'!
```
Is this a relative path issue or could it be a bug?

* I'm running on windows 10 PC through git bash.
* (cbuildgen): Build Process Manager 0.10.3 (C) 2021 ARM
Date: Aug  5 2021 Time: 07:38:56

Regards,
Enver

**Comment by brondani** [comment]
Hi @enversultanov

From the error message it seems there are too many quotation marks in the include path.
Can you please check the generated cprj? I expect a correct include path would look like this:
```
<includes>../Module Name/include</includes>
```
Are you using the [latest MDK](https://www2.keil.com/mdk5)?
CMSIS-Build and CMSIS-Toolbox (which includes CMSIS-Build) have also [newer releases](https://github.com/Open-CMSIS-Pack/devtools/releases).

Thanks
Daniel

**Comment by enversultanov** [comment]
Hi Daniel!

Here is how the include looks like:

`<includes>"../Module Name/include";../../Module2 Name/inc</includes>`

Removing the extra quotation marks solved the issue.

Thanks for the links, I will make sure to use the latest version.

Regards,
Enver
