### ISSUE TITLE
Missing Bias `NULL` Check in Optimized Depthwise Convolutions

### ISSUE THREAD

**Issue by fpedd** [ARM-software/CMSIS_5#1505]
In #1360 a bias null check was added to the default (fallback) dw conv [`arm_depthwise_conv_s8.c`](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8.c#L228) functions along with unit tests. However, no check was added to the optimized dw conv functions [`arm_depthwise_conv_s8_opt.c`](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_s8_opt.c#L179) and [`arm_depthwise_conv_3x3_s8.c`](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_3x3_s8.c#L104) that get called from the [`arm_depthwise_conv_wrapper_s8.c`](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_conv_wrapper_s8.c#L69). The unit tests that were added in #1360 also only call [`arm_depthwise_conv_s8.c`](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c#L504) directly and never the wrapper. Hence, no unit tests with `bias = NULL` run over the specialized functions and cause a failure. Is this intended, or should the specialized functions also be able to handle the `bias = NULL` case?

Also: These redundant calls to  `arm_depthwise_conv_s8` [here](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c#L441) and [here](https://github.com/ARM-software/CMSIS_5/blob/61ad1303bc50450130cfb540caa384875a260b91/CMSIS/NN/Tests/UnitTest/TestCases/test_arm_depthwise_conv_s8/test_arm_depthwise_conv_s8.c#L441) probably meant to call `arm_depthwise_conv_wrapper_s8`, right?

Let me know and if indeed not intended, I can open PRs for this.

**Comment by felix-johnny** [comment]
@fabianpedd Thanks for the reporting this. The bias check is should be a part of the specialized functions as well. 

As for calling the functions directly in the unit tests, we do it on a case by case basis as some functions could be specific to an architecture(e.g arm_depthwise_conv_3x3_s8()). But for the redundant calls that you mention at the end, one of those should call the wrapper. 
  You are welcome to open PR's for this!

**Comment by felix-johnny** [comment]
@fabianpedd  I've pushed the fix.. You can try with that..

**Comment by fpedd** [comment]
Great, thanks! I apologize for taking so long to do it myself. I will give everything a try.
