### ISSUE TITLE
How to get RTOS2 RTX v5 Library Files?

### ISSUE THREAD

**Issue by niliqiang** [ARM-software/CMSIS_5#1518]
Hi all,
I am trying to get the RTX v5 library files via fetch_libs.sh, but it returns like below: 
![image](https://user-images.githubusercontent.com/41098158/177454856-171ea7cb-c169-48ec-afda-e6c661de3deb.png)
and it seems I don't have access to https://artifactory.eu02.arm.com:443/ui/admin/artifactory/user_profile
Does anyone know how to get ARTIFACTORY_API_KEY? thx!

**Comment by JonatanAntoni** [comment]
Hi @niliqiang,

Unfortunately, this resource is not publicly accessible.
You can either build the libs on your own. Or you can find all the binary content (which is not in the repo) in the official release packs.

Moving the full CI/CI pipelines to public resources is still on our backlog. It will take us more time to work on that.

Thanks for getting in touch,
Jonatan

**Comment by niliqiang** [comment]
Thank you very much for your explanation, I got the library files in the official release packs.
