### ISSUE TITLE
IAR: ALIGNED not supported warning in the header file might result in lot of warnings

### ISSUE THREAD

**Issue by 0xc0170** [ARM-software/CMSIS_5#152]
The warning is fine to warn a user that something is not supported by a compiler but the placement of this warning might be counterproductive - in a header file. It's currently in a header that is being included everywhere as it's part of CMSIS. Therefore when a user compiles their code, it might end up with 100x warnings (all are the same, for each file that depends on CMSIS). It creates lot of noise, that will result in removing this warning after few compilations :-)

Here's the warning:
``  [Pe1105]: #warning directive: No compiler specific solution for __ALIGNED. __ALIGNED is ignored.``

I would suggest to have one code file  that would warn about this - warning: this feature of cmsis is not supported by this compiler. Or remove that warning and document it what is supported and what not (a user should be aware some extensions are not supported - they are compiler specific. - thus a code using it might not be portable.

**Comment by ReinhardKeil** [comment]
I think you should be able to use a compiler directive that effectively inserts an #define __ALIGNED. In this way you can avoid the issue.

P.S. IAR is working on a solution to that problem.

**Comment by 0xc0170** [comment]
I am missing how this was resolved (DONE label) ? The warning was removed? IAR new version needed or?

**Comment by JonatanAntoni** [comment]
IAR seems to have solved the issue. With EW-ARM 7.80.4 IAR ships a `cmsis_iar.h` header file containing the required macro definition as 
```
#ifndef __ALIGNED
#define __ALIGNED(x) __attribute__((aligned(x)))
#endif
```

**Comment by 0xc0170** [comment]
I'll close this issue, thanks!
