### ISSUE TITLE
CMSIS-DSP：Why the Q15 type of matrix multiplication is transposed, while its Q31 type is not transposed

### ISSUE THREAD

**Issue by JoleenSun** [ARM-software/CMSIS_5#1524]
1.  I'm curious about why a transposition is carried out before multiplication in the function arm_mat_mult_fast_q15 , while there is no transposition in the function arm_mat_mult_fast_q31. But transposition can also bring better performance for function arm_mat_mult_fast_q31 actually.
2.  Function arm_mat_mult_q15 also has an input "pState", but also has not do the transposition.
Would you please give an explanation？Thanks a lot!

**Comment by christophe0606** [comment]
@JoleenSun Thanks for the question.
Could you ask the question again on the new CMSIS-DSP repository : https://github.com/ARM-software/CMSIS-DSP

Because the answer may interest other people so I'd prefer to answer on the new repository.

Thank you.
