### ISSUE TITLE
validator should check if base address + offset is larger than adress space

### ISSUE THREAD

**Issue by odinthenerd** [ARM-software/CMSIS_5#154]
[Here](https://github.com/posborne/cmsis-svd/blob/master/data/STMicro/STM32L15xxE.svd#L4172-L4183) there is a register who's address is larger than the address space (larger than 0xFFFFFFFF). The CMSIS-SVD validator should be checking this kind of thing so that vendors cannot make this kind of mistake.

This was originally discovered [here](https://github.com/kvasir-io/Kvasir/issues/108)

**Comment by JonatanAntoni** [comment]
Commit e121811343c9f2c659d1bee19c3b0ab6aaa5e944 adds this check. Please review the solution and close this issue.

**Comment by JonatanAntoni** [comment]
Closed due to inactivity.
