### ISSUE TITLE
Inverted parameters in MMU_GetSectionDescriptor() and MMU_GetPageDescriptor()

### ISSUE THREAD

**Issue by ANOSTM** [ARM-software/CMSIS_5#1612]
Hello,

In CMSIS v5.8.0 (and also in v5.9.0), some parameters are inverted in CMSIS/Core_A/Include/core_ca.h
The call of MMU_APPage and MMU_APSection are not aligned with their definitions ( user <> priv).
See below

- MMU_GetSectionDescriptor()
![image](https://user-images.githubusercontent.com/46556619/226918079-5db0d563-041d-4c0e-91e8-963fb8d5862c.png)

- MMU_GetPageDescriptor()
![image](https://user-images.githubusercontent.com/46556619/226918597-f4f8c956-31b6-48d0-9328-2cd16dcf0e0f.png)

**Comment by JonatanAntoni** [comment]
Thanks for pointing this out.
May I ask you to raise this change as a PR against develop branch, please?

**Comment by ANOSTM** [comment]
Could you confirm that you mean Pull Request by PR ?

**Comment by JonatanAntoni** [comment]
Yes, I mean Pull Request ;)

**Comment by ANOSTM** [comment]
I created a pull request from a fork : https://github.com/ANOSTM/CMSIS_5/pulls
Is it OK for you ?

**Comment by JonatanAntoni** [comment]
You need to raise the PR against this repo, not internally to your personal fork.

**Comment by ANOSTM** [comment]
Hello,

After some discussion, I raised https://github.com/ARM-software/CMSIS_5/pull/1613
I saw this PR (1613) has been merged.
So probably the patch is already available, and this PR (1612) can be closed.
Could you confirm ?

**Comment by ghost** [comment]
Hello @ANOSTM, this PR can be closed.
The requested changes are already merged with #1613

**Comment by JonatanAntoni** [comment]
Thanks, @GuentherMartin, I overlooked that.
