### ISSUE TITLE
cmsis_os.h '__NO_RETURN' macro redefined

### ISSUE THREAD

**Issue by vahle-at-gpi** [ARM-software/CMSIS_5#1615]
I have migrated a CMSIS RTOS based projects from Arm Compiler 5 to Arm Compiler 6.
Now i got a lot of warnings like 
`"cmsis_os.h(73): warning: '__NO_RETURN' macro redefined [-Wmacro-redefined]"`
The root cause is that '__NO_RETURN' is defined in 'cmsis_armclang.h' and 'cmsis_os.h'.

Following line(s) in "cmsis_os.h" need to be changed from
`#define __NO_RETURN __attribute__((noreturn))`
to
`#ifndef __NO_RETURN`
`#define __NO_RETURN __attribute__((noreturn))`
`#endif`

Please fix that in next release.

**Comment by JonatanAntoni** [comment]
Hi @gpi-v,

CMSIS-RTOS has been deprecated for long time and won't receive any updates anymore. With the upcoming major CMSIS update we'll drop CMSIS-RTOS completely. I recommend updating to RTX5 and CMSIS-RTOS2.

Cheers,
Jonatan
