### ISSUE TITLE
Output Mismatch in ARM mult , scale, Complex real mult in CMSIS 5.9 version

### ISSUE THREAD

**Issue by BhaskarsarmaP** [ARM-software/CMSIS_5#1641]
<img width="233" alt="image" src="https://github.com/ARM-software/CMSIS_5/assets/37923435/fd0c50f7-c0a2-446a-89e1-3bf4b2faf3e9">

Here, As shown in the image above (https://github.com/ARM-software/CMSIS_5/blob/5.9.0/CMSIS/DSP/Source/BasicMathFunctions/arm_mult_q31.c) For q31 case, we are first right shifting and then left shifting by a bit which results in precision loss of LSB.
When this is run multiple times, It can result in a huge loss of data.

For q15, q7 it is handled correctly like below.
<img width="292" alt="image" src="https://github.com/ARM-software/CMSIS_5/assets/37923435/62c03d0a-3fa3-44a3-b741-59158ca9db20">

The issue also exists for mult, scale, and other cases where q31 mult operations are involved. 

Please let us know the plans for fixing this.

**Comment by JonatanAntoni** [comment]
Hi @BhaskarsarmaP,

Please raise your CMSIS-DSP issue at the new repository
https://github.com/ARM-software/CMSIS-DSP.

Thanks,
Jonatan
