### ISSUE TITLE
Error in the description of CMSIS-SVD

### ISSUE THREAD

**Issue by AndreySmirnov81** [ARM-software/CMSIS_5#1646]
![изображение](https://github.com/ARM-software/CMSIS_5/assets/19325847/8f6701ea-3138-412c-872b-cdea2135e5fa)

**Comment by JonatanAntoni** [comment]
Please find the latest SVD spec at the new location
https://github.com/Open-CMSIS-Pack/svd-spec

The highlighted parts are still the same. Can you please raise this issue in the new location and be a bit more verbose about the issue you are facing?
