### ISSUE TITLE
How to build a library in the Ti env.

### ISSUE THREAD

**Issue by yanlong658** [ARM-software/CMSIS_5#1650]
Excuse me,
Currently, I am configuring the environment for CMSIS-DSP on TI CCS (9.),but I am unsure how to configure it to generate a .lib file for the M4 core. I'm not sure if anyone knows how to do this.

Thanks all.

**Comment by JonatanAntoni** [comment]
Hi @yanlong658,

This sounds like a question regarding the toolchain you are using.
Please note we are in the progress of moving to [CMSIS 6](https://github.com/ARM-software/CMSIS_6) and CMSIS 5 is not planned to receive further updates.

You could check CMSIS command line build tools in [CMSIS-Toolbox](https://github.com/Open-CMSIS-Pack/cmsis-toolbox). There is a target option to select between executable and library output. For details about TI Code Composer Studio you'd better raise this question in the according forum.

Cheers,
Jonatan
