### ISSUE TITLE
SVDConv utilities are out-of-sync with CMSIS-SVD schema version 1.3.3

### ISSUE THREAD

**Issue by eperie** [ARM-software/CMSIS_5#169]
Version impacted: 729bd0ba738a4c5e695fe6a23d2a0d787e7b73a1, and likely CMSIS 5.0.1 - not verified yet.
Steps to reproduce issue:

1. Add the following line after line 62 of ARM_Example.svd:
`<vendorSystickConfig>false</vendorSystickConfig`
becomes:
`<vendorSystickConfig>false</vendorSystickConfig`
`<deviceNumInterrupts>15</deviceNumInterrupts>`
2. Validate modified ARM_Example.svd against CMSIS-SVD.xsd using xmllint:
`xmllint --schema CMSIS-SVD.xsd ARM_Example.svd`
  modified ARM_Example.svd does validate:
_ARM_Example.svd validates_
3. Attempt to generate header file from modified  ARM_Example.svd:
`Linux-gcc-4.8.3/SVDConv ARM_Example.svd --generate=header`

_CMSIS-SVD SVD Consistency Checker / Header File Generator V3.3.4
Copyright (C) 2010 - 2017 ARM Ltd and ARM Germany GmbH. All rights reserved.
Arguments: "ARM_Example.svd" --generate=header
*** ERROR M201: ARM_Example.svd (Line 63)
  **Tag \<deviceNumInterrupts\> unknown or not allowed on this level.**
*** INFO M317: ARM_Example.svd (Line 91)
  Interrupt \<description\> not set.
*** WARNING M208: ARM_Example.svd (Line 752)
  Ignoring \<dimIndex\> because specified \<name\> requires Array generation.
*** INFO M317: ARM_Example.svd (Line 771)
  Interrupt \<description\> not set.
*** INFO M317: ARM_Example.svd (Line 781)
  Interrupt \<description\> not set.
Found 1 Error(s) and 1 Warning(s)._

All versions of SVDConv (two Linux and one Win32) show the same behaviour.

Suggestions:

- Providing versions of SVDConv in sync with lastest 1.3.3 schema version if the schema is to stay as is (prefered), or commenting-out not yet supported constructs in current schema file,
- Updating ARM_Example.svd to 1.3.3 schema standard if issue is to be fixed.

**Comment by JonatanAntoni** [comment]
Thank you for your report. We will update SVDConv.

**Comment by eperie** [comment]
Thank you for having taken this report into consideration.

**Comment by JonatanAntoni** [comment]
Hi @eperie,

sorry for not reporting back here for long.
We have updated SVDConv to 3.3.13 in the meanwhile. This issue should be solved.
May I ask you to double check and close, please?

Thanks,
Jonatan

**Comment by eperie** [comment]
Regressed in v5.3.0 - thanks.
Éric
