### ISSUE TITLE
RTOS : Questions about RTOSv1 license

### ISSUE THREAD

**Issue by ykabe** [ARM-software/CMSIS_5#174]
Hi, I have a question about this repositry software license.
According to http://www.keil.com/pack/doc/CMSIS/RTOS/html/rtxImplementation.html, the software license of RTOSv1 is BSD.
However, according to LICENSE.txt, this repository software is Apache License 2.0.
the software license of "CMSIS_5 / CMSIS / RTOS / RTX / folder" is Apache License 2.0? Or BSD?

**Comment by jkrech** [comment]
Sorry for the confusion. It is supposed to be Apache 2.0. We will update the source code header sections accordingly.

**Comment by ykabe** [comment]
Thank you for your prompt response.
I understand that it is Apache 2.0.

**Comment by JonatanAntoni** [comment]
Work is in progress. I give you feedback as soon as the update is done.

**Comment by ykabe** [comment]
Thank you for your support.
When do you plan to complete the fix?

**Comment by ykabe** [comment]
Thank you for your support.
When do you plan to complete the fix?

**Comment by ykabe** [comment]
I'm sorry,I accidentally closed it.

**Comment by JonatanAntoni** [comment]
We aim to resolve this issue with the upcoming CMSIS 5.1.0 release. Do you have time constraints here?

**Comment by ykabe** [comment]
I would like to use RTX 4.82 on our products.
However, the code fix is near.
Is it possible to hurry to correct the RTOS folder?

**Comment by JonatanAntoni** [comment]
Yes. I am going to address this soon. Its simply a matter of capacity at our side I have to manage.

**Comment by ykabe** [comment]
Thank you for your support in your busy time.
We are expecting an early correction.

**Comment by JonatanAntoni** [comment]
@ykabe I recently updated all the license comments for CMSIS-RTX on develop branch. May I ask you to review the changes? Please close this issue if your concerns are solved.

**Comment by ykabe** [comment]
I confirmed that the change contents are satisfactory.
Thank you for your help despite how busy you are.
