### ISSUE TITLE
EXTI in the CMSIS Driver

### ISSUE THREAD

**Issue by ghost** [ARM-software/CMSIS_5#181]
Excuse me, Why not CMSIS Driver support EXTI?

**Comment by JonatanAntoni** [comment]
Hi @809205580. We have currently no CMSIS Driver API for GPIO related operations defined. May I ask you to provide us some use cases you would like to have such an API for? What should the API look like to be useful?

**Comment by 809205580** [comment]
I have used GPIO driver(used by RTE Drivers for STM32F1), but I didn't find the operation associated with the interrupt used for button or key.

**Comment by JonatanAntoni** [comment]
Please be more specific. Which GPIO driver do you use? I assume the STM32Cube one? This is the native driver API provided by STM, not a CMSIS one.

The STM32Cube (and the older STM32Peripheral Library) provide some support for EXTI configuration. If you have detailed questions about the STM32 library implementation please consider to contact the ST community. I am glad to discuss CMSIS related issues here.

**Comment by JonatanAntoni** [comment]
@809205580 do you have any further concerns about EXTI handling with CMSIS? Otherwise I would kindly ask you to close this issue please.

**Comment by 809205580** [comment]
OK.

**Comment by JonatanAntoni** [comment]
Closing due to no further open questions to be discussed. Please feel free to reopen if you still have any concerns.
