### ISSUE TITLE
CMSIS kernels for neural networks

### ISSUE THREAD

**Issue by liangzhen-lai** [ARM-software/CMSIS_5#187]
Hi, 

We have been writing some computation kernels for running different neural networks on cortex-m based systems using some of CMSIS functions. 

We think it might be good to include these in CMSIS-DSP. What would be the best way for this?

Here is an example of a convolution function using CMSIS functions:
[convolution_example.txt](https://github.com/ARM-software/CMSIS_5/files/953357/convolution_example.txt)

Thanks,
Liangzhen

**Comment by JonatanAntoni** [comment]
Thank you for your contribution. I will come back to you as soon as our workload allows.
