### ISSUE TITLE
CMSIS DSP: arm_math warnings for ARMCC 5.2x

### ISSUE THREAD

**Issue by 0xc0170** [ARM-software/CMSIS_5#188]
This is the output if ARMCC is used with ``--gnu`` flag (thus ``__GNUC__`` is defined). This is causing the following warnings:

```
[Warning] arm_math.h@298,0:  #2803-D: unrecognized GCC pragma
[Warning] arm_math.h@299,0:  #2803-D: unrecognized GCC pragma
[Warning] arm_math.h@300,0:  #2803-D: unrecognized GCC pragma
[Warning] arm_math.h@301,0:  #2803-D: unrecognized GCC pragma
[Warning] arm_math.h@4949,0:  #3108-D: attribute "__packed__" does not apply here
[Warning] arm_math.h@4957,0:  #3108-D: attribute "__packed__" does not apply here
[Warning] arm_math.h@7218,0:  #2803-D: unrecognized GCC pragma
```

This is causing pragma warnings: https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Include/arm_math.h#L297 (one more line in the end of the file also). The pragma are easy to fix - add "not defined ARMCC" : ``#if defined(__GNUC__) && !defined ( __CC_ARM )``.  I'll can send a patch for review

However, how  to fix the ``__packed__`` attribute?

I have installed armcc 5.23 that I am testing with.

**Comment by 0xc0170** [comment]
Proposed fix : https://github.com/ARM-software/CMSIS_5/pull/189

**Comment by christophe0606** [comment]
There were several changes to arm_math.h since this issue was opened.

I'll think this issue is fixed. Feel free to reopen it if you still have the problem.
