### ISSUE TITLE
When building for Cortex-M33, defining ARM_MATH_CM33, arm_math.h errs

### ISSUE THREAD

**Issue by Patater** [ARM-software/CMSIS_5#195]
## What's happening?
When building for the Cortex-M33 target, defining `ARM_MATH_CM33`, `arm_math.h` gives the error:

```
./mbed-os/cmsis/arm_math.h:329:4: error: #error "Define according the used Cortex core ARM_MATH_CM7, ARM_MATH_CM4, ARM_MATH_CM3, ARM_MATH_CM0PLUS, ARM_MATH_CM0, ARM_MATH_ARMV8MBL, ARM_MATH_ARMV8MML"
   #error "Define according the used Cortex core ARM_MATH_CM7, ARM_MATH_CM4, ARM_MATH_CM3, ARM_MATH_CM0PLUS, ARM_MATH_CM0, ARM_MATH_ARMV8MBL, ARM_MATH_ARMV8MML"
    ^~~~~
```
https://github.com/ARM-software/CMSIS_5/blob/5480572144bead2e5323ad3d72ad2140dd85f721/CMSIS/DSP/Include/arm_math.h#L329

## Workaround

I can workaround the issue by defining `ARM_MATH_ARMV8MML` instead, but that's the old name for the M33.

## Expected behavior

`arm_math.h` should behave properly when `ARM_MATH_CM33` or `ARM_MATH_CM23` are defined. Documentation and project files referring to the old name for the Cortex-M33 and Cortex M-23 should be updated.

**Comment by christophe0606** [comment]
This no more applies since arm_math.h has been modified and is no more doing those checks.
