### ISSUE TITLE
Problem with Recursive mutex

### ISSUE THREAD

**Issue by juliobc** [ARM-software/CMSIS_5#200]
Hi. 
I am using a recursive mutex in my app and I saw that it is running well but in a random time the funtion osMutexAcquire() returns != osOK when it is called from the owner thread, and then the aplication fails.

I only use osMutexRecursive attibute, not osMutexPrioInherit and not osMutexRobust.

What is the funtionality of osMutexRobust?? Some clue?

**Comment by juliobc** [comment]
I saw that Lock Counter is 0xFF when the problem exists

**Comment by juliobc** [comment]
Sorry, I did not know that the mutex had to be released every time it was acquired by the owner every time. Solved

**Comment by JonatanAntoni** [comment]
Hi @juliobc. Thank you for your feedback.
I think our documentation has room for improvement here.
I am going to add some more details and short examples to the Mutex Flags. Thus I reopen this issue.
It would be nice if you could give it a review.

**Comment by JonatanAntoni** [comment]
Please find additional documentation attached to the mutex macro definition.
Does this makes things clear?

**Comment by juliobc** [comment]
Hi @JonatanAntoni, 
Great. 
Thank you

**Comment by JonatanAntoni** [comment]
Please close the issue if you do not have additional feedback.
