### ISSUE TITLE
How to multiply fractional data?

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS_5#223]
<arm_math.h> defines several types of fractional data (i.e. q7_t,q15_t, q31_t, ...) and some useful functions to perform operations on vectors [are exposed](https://www.keil.com/pack/doc/cmsis/dsp/html/group__groupMath.html).
Sometimes I need to do these basics operation (addition, subtraction, ...) between two single values, and not a vector.
Should I call the same functions with `blockSize` set to 1?
Is this the optimized way to proceed?
Or should I use some basic functions defined in <arm_math.h> (__QADD, _QSUB, ...)?

**Comment by xizhizhang** [comment]
there are not optimized yet, just use __QADD.
