### ISSUE TITLE
RTX5 – RTX RTOS Viewer – allocated global dynamic memory

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#224]
It would be an interesting information how much memory is allocated in the “Global Dynamic Memory”.
Is it possible to include this information in RTX RTOS Viewer (RTX5.svcd)?

**Comment by JonatanAntoni** [comment]
Hi @FerdinandEn,

I added the used counter for global dynamic memory to RTX Component Viewer with commit 8cbaa7d.
Can you please verify if this works as you expect?

Thanks,
Jonatan

**Comment by FerdinandEn** [comment]
Hi Jonatan,
Thanks, It works fine.

Ferdinand
