### ISSUE TITLE
Incorrect M33 TPI FIFO0 and FIFO1 Macro Definitions and Comments

### ISSUE THREAD

**Issue by kappajacko** [ARM-software/CMSIS_5#243]
The M33 TRM describes how to connect the ITM and ETM to the TPIU.

> B.2 TPIU Functional Description
...
In a system, ARM recommends that the ITM is connected to ATB port 1 and an ETM is connected to
ATB port 2.

However, the CMSIS for M33 is using the old M3/4/4H TPI definitions where ETM was connected to ATB1 and ITM was connected to ATB2.

It looks like a classic copy paste ERROR in the core_cm33.h with respect to the TPI macros.  All of the macros associated with ATB1 are named with ETM instead of ITM and all the macros associated with ATB2 are named ITM instead of ETM.

**Comment by JonatanAntoni** [comment]
Hi @kappajacko, may I ask you to review the provided changes, please? Do this solve your concerns? If yes, please consider closing this issue. Thanks.
