### ISSUE TITLE
PDSC: The Cgroup=CORE spelling is inconsistent with the documentation

### ISSUE THREAD

**Issue by oakm** [ARM-software/CMSIS_5#247]
[CMSIS documentation](https://www.keil.com/pack/doc/CMSIS/Pack/html/element_taxonomy.html#CgroupType) lists Cgroup=Core for one of the predefined values for the Component Class Cclass="CMSIS". This however is all in UPPERCASE in the ARM.CMSIS.pdsc file.

`<component Cclass="CMSIS" Cgroup="CORE" Cversion="5.0.2"  condition="ARMv6_7_8-M Device" >`

**Comment by JonatanAntoni** [comment]
Indeed, the documentation is wrong here. Thanks for making me aware. I'll fix that soon.

**Comment by JonatanAntoni** [comment]
Hi @oakm,

May I ask you to double check if my changes fit your expectation, please?

Many thanks,
Jonatan

**Comment by oakm** [comment]
Hi Jonatan,

Looks good.

Thanks,
Orest
