### ISSUE TITLE
Secure functions not accessible from Timer/Idle thread

### ISSUE THREAD

**Issue by deepikabhavnani** [ARM-software/CMSIS_5#252]
Idle and Timer threads in RTX, should have configurable option for osThreadAttr_t::tz_module
https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/RTOS2/RTX/Source/rtx_lib.c#L131

@bulislaw @c1728p9 @sg-

**Comment by deepikabhavnani** [comment]
Any update on this?

**Comment by JonatanAntoni** [comment]
Sorry for the delay, we have been busy the last weeks. We are going to look into this issue soon.

**Comment by RobertRostohar** [comment]
TrustZone Module ID can now be configured also for Idle and Timer Thread.
