### ISSUE TITLE
Stack Pointer Issue - Systick handler

### ISSUE THREAD

**Issue by deepikabhavnani** [ARM-software/CMSIS_5#257]
In case of non-secure code, stack pointer was not getting updated properly whenever context switched to another thread.

Issue at https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/RTOS2/RTX/Source/GCC/irq_armv8mbl.S#L232
Instead of LR R7 is used to check if in secure/non-secure mode.

Correct Code
-LSLS     R7,R7,#25              // Check domain of interrupted thread
 -BMI      Sys_ContextSave1       // Branch if secure

+MOV     R0, LR
+LSLS     R0,R0,#25              // Check domain of interrupted thread
+BPL      Sys_ContextSave1       // Branch if non-secure

CC @c1728p9

**Comment by RobertRostohar** [comment]
Thank you for reporting the issue and providing the correction. PR #260 has been merged,
