### ISSUE TITLE
Question on arm_abs_q31 implementation

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS_5#273]
Source code of arm_abs_q31.c uses
`*pDst++ = (in1 > 0) ? in1 : (q31_t)__QSUB(0, in1);`
the following when it computes 4 outputs at a time and the comment says
`/* Calculate absolute of input (if -1 then saturated to 0x7fffffff) and then store the results in the destination buffer. */`

In the bottom part of the same file, when it computes the remaining outputs, the source code is a little bit different (to handle the saturation, I think)
`*pDst++ = (in > 0) ? in : ((in == INT32_MIN) ? INT32_MAX : -in);`

Are the above implementations somehow different (in terms of behavior and/or performance)?
Or are they the same?

Thanks

**Comment by llefaucheur** [comment]
Hi, you are true this inconsistency creates confusion and we will align the methods. The answer to your question depends on the processor, compiler and optimisation configuration. 
From a programmer's point of view you could also implement a different algorithm if you know most of your data have a known sign, and you want to optimise the amount of program-counter disruptions in the if/then/else.

**Comment by escherstair** [comment]
Thank you.
