### ISSUE TITLE
Suggestion: Expose a __DCACHE_LINE_SIZE constant in core_cm7.h

### ISSUE THREAD

**Issue by udoe** [ARM-software/CMSIS_5#282]
Such a standardized constant would be very useful as the cache line size must be known in higher software layers, e.g. to align buffers properly.

Thanks
Udo

**Comment by GuentherMartin** [comment]
Hello @udoe could you please check the new define and close the issue.

**Comment by udoe** [comment]
Looks ok to me. Thanks.
