### ISSUE TITLE
CORE: _VAL2FLD macro, passed parameter 'value' should be cast to uint32_t

### ISSUE THREAD

**Issue by franzhollerer-Artesyn** [ARM-software/CMSIS_5#3]
Please change the macro

```c
#define _VAL2FLD(field, value)    ((value << field ## _Pos) & field ## _Msk)
```

to

```c
#define _VAL2FLD(field, value)    (((uint32_t) (value) << field ## _Pos) & field ## _Msk)
```

Rational: Without the cast the compiler issues the warning below if a bit it shifted to the sign bit.

> foo.c(xxx): warning:  #68-D: integer conversion resulted in a change of sign

Note: Issue already discussed with Reinhard Keil. Thus this is just a reminder...

**Comment by GuentherMartin** [comment]
Included in CMSIS-Core.
