### ISSUE TITLE
cmsis_cp15.h: __set_CCSIDR is a wrong name

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS_5#300]
Wrapper name __set_CCSIDR looks like wrong. This register read-only, returns information depend on CSSELR. Right name is __set_CSSELR.

**Comment by JonatanAntoni** [comment]
Thanks for pointing this out, @ua1arn. In fact `__set_CCSIDR` already affected `CSSELR`. 

May I ask you to double check the fix I applied in 259c17e, please?

Best,
Jonatan

**Comment by ua1arn** [comment]
Thank you. Body of __set_CSSELR has a right code.

**Comment by ua1arn** [comment]
Tested on Renesas R7S721020VCFP#AA0 (standalone application) - work as expected.
