### ISSUE TITLE
__set_MVBAR, __get_MVBAR, __set_VBAR, __get_VBAR

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS_5#301]
See 4.2.13. c12 registers in http://infocenter.arm.com/help/topic/com.arm.doc.ddi0388i/DDI0388I_cortex_a9_r4p1_trm.pdf

__set_VBAR use __set_CP(15, 0, vbar, 12, 0, 1) - this opcode for Monitor Vector Base Address Register

Vector base address should be accessed trough __set_CP(15, 0, vbar, 12, 0, 0)

Proposed code:

 /** \brief  Get MVBAR

    This function returns the value of the Monitor Vector Base Address Register.

    \return               Monitor Vector Base Address Register
 */
__STATIC_FORCEINLINE uint32_t __get_MVBAR(void)
{
  uint32_t result;
  __get_CP(15, 0, result, 12, 0, 1);
  return result;
}

/** \brief  Set MVBAR

    This function assigns the given value to the Monitor Vector Base Address Register.

    \param [in]    mvbar  Monitor Vector Base Address Register value to set
 */
__STATIC_FORCEINLINE void __set_MVBAR(uint32_t vbar)
{
  __set_CP(15, 0, vbar, 12, 0, 1);
}

 /** \brief  Get VBAR

    This function returns the value of the Vector Base Address Register.

    \return               Vector Base Address Register
 */
__STATIC_FORCEINLINE uint32_t __get_VBAR(void)
{
  uint32_t result;
  __get_CP(15, 0, result, 12, 0, 0);
  return result;
}

/** \brief  Set VBAR

    This function assigns the given value to the Vector Base Address Register.

    \param [in]    vbar  Vector Base Address Register value to set
 */
__STATIC_FORCEINLINE void __set_VBAR(uint32_t vbar)
{
  __set_CP(15, 0, vbar, 12, 0, 0);
}

**Comment by JonatanAntoni** [comment]
Hi @ua1arn,

Thanks for reporting. May I ask you to double check the fix I added with 0ac0276, please?

Best,
Jonatan

**Comment by ua1arn** [comment]
In part of function bodies looks fine.

**Comment by JonatanAntoni** [comment]
Issue should be solved. Please feel free to reopen if any questions left.

**Comment by ua1arn** [comment]
Tested on Renesas R7S721020VCFP#AA0 (standalone application) - work as expected.

**Comment by JonatanAntoni** [comment]
Great, many thanks for your additional testing efforts.
