### ISSUE TITLE
Unnecessary 'volatile' in core_ca.h

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS_5#303]
Who can explain needs for use 'volatile' attribute in variables in __L1C_MaintainDCacheSetWay and L1C_CleanInvalidateCache, for example.
Hide from compiler optimizations already done by 'volatile' in definition of __get_CP and __set_CP.

**Comment by JonatanAntoni** [comment]
Thanks for pointing this out. The functions were refactored a while ago. We missed to remove the unnecessary `register volatile` declaration.

**Comment by JonatanAntoni** [comment]
@ua1arn may I ask you to double check the cleanup made in 509ae42, please?

**Comment by ua1arn** [comment]
All okay. Thank you.
