### ISSUE TITLE
CMSIS-RTOS 2 - open for review after Milestone RTOS_doc1

### ISSUE THREAD

**Issue by ReinhardKeil** [ARM-software/CMSIS_5#32]
Please do not submit any comments at this point in time as we are still working on it.

**Comment by ilg-ul** [comment]
Did you set any date for this milestone?

**Comment by ilg-ul** [comment]
Does the new documentation mentioned in #72 (Sep. 14, 2016) mean that this milestone was reached and the RTOSv2 is open for review?

**Comment by ReinhardKeil** [comment]
we are now clearly in the review phase - sorry when I was not precise before

**Comment by ilg-ul** [comment]
perhaps you could update the milestones and their use, as of now they might not be very useful.
