### ISSUE TITLE
Suggestion to add bit- macros for EXC_RETURN/Integrity Signature flags

### ISSUE THREAD

**Issue by ioannisg** [ARM-software/CMSIS_5#340]
As a developer, implementing **exception & fault handling** functions for Cortex-M MCUs, I would like to have standard (CMSIS) bit-mask macro #defines for EXC_RETURN flags, namely, ES, SPSEL, Mode, S, Ftype etc., so I would not have to define those in OS/application source code. 

Particularly for ARMv8-M with Security Extension: I would also like to have a macro definition for the value of the Integrity Signature.

**Comment by JonatanAntoni** [comment]
Hi @ioannisg,

Thanks for getting in touch about this.
At the first glance your suggestion looks reasonable to me. Are you willing to collaborate? A pull-request with the proposed enhancements is very appreciated.

Cheers,
Jonatan

**Comment by ioannisg** [comment]
@JonatanAntoni Yes, I can work on an PR for this one. Will keep you posted.

**Comment by JonatanAntoni** [comment]
Great. That would be very helpful as team capacity is always the limiting factor. Thanks.

**Comment by ReinhardKeil** [comment]
We added added defines to CMSIS-Core(M) for EXC_RETURN values.

Sorry we have not found the value of Integrity Signature (is this documented somewhere? why is this value important as it is checked by HW only?)

**Comment by salkinium** [comment]
> is this documented somewhere?

In the ARMv8-M ARM. Quite literally.

<img width="730" alt="screen shot 2018-05-28 at 17 46 14" src="https://user-images.githubusercontent.com/163066/40621868-1c6c9500-629f-11e8-9d96-f50a3eefa355.png">

**Comment by ioannisg** [comment]
@ReinhardKeil thanks a lot for the update; the reasoning behind having the needs to check the Integrity Signature in Software could be as follows:

Assume a Cortex-M33 with Security Extensions.
In a SecureFault handler the developer needs to handle SecureFault exception triggered by Non-Secure code.
It is straightforward to dump the Non-Secure stack information. However, the developer may want to also dump the Secure stack information, too.
Now, if the fault has occurred during a Non-Secure exception which has interrupted the Secure execution, the Secure state has stacked the additional state context and the top of the stack contains the **integrity signature**. [In case of a Non-Secure function call the top of the stack contains the return address to Secure state.]
The integrity signature is needed, in order to see if there is also the additional context.

**Comment by JonatanAntoni** [comment]
Hi @ioannisg,

can you confirm that the enhancements provided are functional and fulfill your requirements?
If so, please be so kind and close this issue. 

Cheers,
Jonatan

**Comment by flit** [comment]
@JonatanAntoni It would be best if `EXC_INTEGRITY_SIGNATUR` could be spelled as `EXC_INTEGRITY_SIGNATURE`. Saving a single character is not worth an abnormal spelling. 😄 Thanks!

**Comment by JonatanAntoni** [comment]
Hi @flit, 

Thanks for pointing this out.
We will spent this _huge_ amount of additional disk space ;)

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
Hi @ioannisg, May I ask you to cross check the provided changes and finally close this issue, please?

**Comment by ioannisg** [comment]
> 
> 
> Hi @ioannisg, May I ask you to cross check the provided changes and finally close this issue, please?

Looks good, sorry for delaying this
