### ISSUE TITLE
Documentation issues in trigonometric functions

### ISSUE THREAD

**Issue by m-rest** [ARM-software/CMSIS_5#344]
Description of interpolation in arm_cos/sin_f32.c uses different variable names for text (a,b) and code example (b,c). Actual code uses (a,b).

  <pre>
The implementation is based on table lookup using 256 values together with linear interpolation.
 The steps used are:
   -# Calculation of the nearest integer table index
   -# Compute the fractional portion (fract) of the table index.
   -# The final result equals <code>(1.0f-fract)*a + fract*b;</code>
 
  where
     b=Table[index+0];
     c=Table[index+1];
  </pre>

In fixed point implementations, code still talks about "four values" from old implementation times:

 `q15_t a, b;                                    /* Four nearest output values */`

**Comment by llefaucheur** [comment]
Hi Maximilian,
You are true, the comments section is creating confusion. Thank you for your time.
Regards, Laurent

**Comment by christophe0606** [comment]
Corrected in commit https://github.com/ARM-software/CMSIS_5/commit/c7efae10ad589a2c2e7f0a0afea53402cf8ec164
