### ISSUE TITLE
CIFAR-10 Caffe model Vs. CMSIS NN implementation.

### ISSUE THREAD

**Issue by iabdalkader** [ARM-software/CMSIS_5#350]
Hi, I was just wondering why the order of layers in the cifar10 example is different than Caffe model ? In the Caffe model, the order of the first 3 layers is conv1, pool1, relu1 while in the CMSIS NN cifar10 example, the functions called are conv, relu and then maxpool. Is there any reason for this ?

**Comment by liangzhen-lai** [comment]
Hi @iabdalkader, no particular reason. relu-maxpool and maxpool-relu should be mathematically identical. conv-pool-relu will run slightly faster.

**Comment by iabdalkader** [comment]
@liangzhen-lai Thanks, I tried conv-pool-relu and it works the same.
