### ISSUE TITLE
How to generate data for Cifar10 Model ?

### ISSUE THREAD

**Issue by baileo** [ARM-software/CMSIS_5#353]
in cifar10 example, the input data range is from -128 to +127.
How to change the RGB image data to this format?
what is the conversion formula?

in my guess, each pixel subtract each channel mean value.
like the following.

R[i] = R[i] - R_avg;
G[i] = G[i] - G_avg;
B[i] = B[i] - B_avg;

**Comment by lishunde** [comment]
see the issuse #346 would help you.
