### ISSUE TITLE
Issues with new TRUE/FALSE definitions

### ISSUE THREAD

**Issue by bulislaw** [ARM-software/CMSIS_5#357]
During update of CMSIS/RTX to 5.3 in Mbed OS we've noticed some changes to type defines, couple of builds for platforms started throwing errors:

```
[Error] rtx_core_cm.h@37,42: missing binary operator before token "1"
[Warning] BLE.h@1049,39: 'virtual ble_error_t Gap::disconnect(Gap::DisconnectionReason_t)' is deprecated: Use disconnect(Handle_t, DisconnectionReason_t) instead. [-Wdeprecated-declarations]
[ERROR] In file included from ./rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_c.h:45:0,
                 from ./rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.h:30,
                 from ./rtos/TARGET_CORTEX/mbed_rtos_storage.h:43,
                 from ./rtos/rtos.h:28,
                 from ./mbed.h:20,
                 from ./features/FEATURE_BLE/targets/TARGET_ARM_SSG/TARGET_BEETLE/source/ArmBLE.cpp:18:
./rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_cm.h:36:42: error: missing binary operator before token "0"
 #define FALSE                   ((bool_t)0)
                                          ^
<command-line>:0:19: note: in expansion of macro 'FALSE'
./targets/TARGET_ARM_SSG/TARGET_BEETLE/cordio/include/wsf/generic/wsf_assert.h:33:5: note: in expansion of macro 'WSF_TOKEN_ENABLED'
 #if WSF_TOKEN_ENABLED == TRUE
```

The changes to `rtx_core_cm.h` that caused above:
```
#include <stdbool.h>
typedef bool bool_t;
#define FALSE                   ((bool_t)0)
#define TRUE                    ((bool_t)1)
```

I don't think it's a correct thing to do as it can't be used with preprocessor, which is perfectly legal, and may be problematic for strict C++98 compilers as the stdbool.h is C99 feature.

@pan- @geky

**Comment by JonatanAntoni** [comment]
Some facts:
- RTX is implemented in C99, not C++98.
- `rtx_core_cm.h` is an internal header file.

We need to figure out what to do for integration. In `stdbool.h´ the C++ keywords `false` and `true` are defined. Maybe we could use them instead of defining `TRUE` and `FALSE`.

**Comment by ReinhardKeil** [comment]
Changing these definitions would trigger MISRA-2012 violations. Why is it required to use this RTX specific header file in your code? Is there some functionality that is not exposed via public API calls?

**Comment by JonatanAntoni** [comment]
@bulislaw please try if using public `rtx_os.h` instead of internal `rtx_lib.h` solves your issue. I expect you try to access the control block sizes when including `rtx_lib.h` through `mbed_rtos_storage.h`, don't you? What else do you need from the internal header?

**Comment by bulislaw** [comment]
We include it in a lot of places for some reason, I'll create an issue to investigate it.

**Comment by ReinhardKeil** [comment]
The public APIs of RTX5 are exposed in the header files https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/RTOS2/RTX/Include

Cmsis-is.h defines the public API. There should be no reason to use any other header in application code.

**Comment by bulislaw** [comment]
Not yet merged to FB.

Bartek

**Comment by ReinhardKeil** [comment]
Closing it now as there is no further information. Please reopen in case that you need further information from us.
