### ISSUE TITLE
What's the meaning of 'multiple-of-4 rows' refferde in arm_fully_connected_q7_opt.c

### ISSUE THREAD

**Issue by lishunde** [ARM-software/CMSIS_5#361]
![image](https://user-images.githubusercontent.com/13815789/39807297-881f45c2-53ae-11e8-9ee4-1e63fc60d54f.png)
It's hard for me to understanded the weight convert style in [arm_fully_connected_q7_opt.c](url)
And I'm import the weight from tensorflow to CMSIS-NN ,which have the shape (10,3136) . 
with the sam input data,I've set all of the biases to 0,but the output always be different .I thought it caused by the False corder of the weight.isn't it?

**Comment by lishunde** [comment]
@liangzhen-lai   I've make a test as shown in the following description

> input:  same  , tensorflow is float16,   cmsis-nn is Quantize to q7_t

>weight:  transform by using the scripe ,and Quantized to q7_t

> biases:  zero
and I  test it by using `tf.matmul(input, weights)`and`tf.nn.relu(tf.matmul(reshape, weights)'respectively ,
but the output  error is relatively  bigger,  May My calculation is not correct.?

**Comment by liangzhen-lai** [comment]
Hi, @lishunde ,

Can you check if the dimension ordering is correct? You can refer to this issue for more details #343 .

Thanks,
Liangzhen

**Comment by liangzhen-lai** [comment]
Can you try the arm_fully_connected_q7 version first? That should be working without weight reordering.
You can also take a look at this [https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations](url) , where we have the reference implementation.

**Comment by lishunde** [comment]
I also make a test by using arm_fully_connected_q7 and arm_fully_connected_q7_ref as it's usage in nn_test.
But the  precision  is also quite different.
The fullly-connect layer make C times multiplication per output  ,it's more larger than conv. isn't the round-off accumulating  cause the error.

**Comment by liangzhen-lai** [comment]
Hi @lishunde ,

Sorry I don't quite understand your question here. Do you mean that the results generated by `arm_fully_connected_q7` and `arm_fully_connected_q7_ref` are different for the same inputs?

Thanks,
Liangzhen

**Comment by lishunde** [comment]
@liangzhen-lai No,I compared the output data bwtween the `arm_fully_connected_q7 or arm_fully_connected_q7_ref`and the tensorflow code.

**Comment by felix-johnny** [comment]
@lishunde Some late tidying up of tickets. The output of _q7 API's cannot be compared with tensorflow as there are multiple differences between them. Please have a look at https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis for more details. 
 Hope that explains.
