### ISSUE TITLE
How to implement a arm_nn_prelu_function?

### ISSUE THREAD

**Issue by baileo** [ARM-software/CMSIS_5#370]
The following is an instance of implementing a arm_nn_prelu_function,

```
void arm_prelu_q7(q7_t * data,
				  const uint16_t dim_im_in,
				  const uint16_t ch_im_in,
				  const q7_t * wt,
				  const uint16_t out_positive_shift,
				  const uint16_t out_negative_shift)
{
    int       prelu_out;
    long dis = dim_im_in*dim_im_in;
    for(int channel =0;channel<ch_im_in; channel++){
        for(int col=0; col<dis; col++){
			if((*data)<0){
					prelu_out = (*data)*(*wt);
					*data = (q7_t) __SSAT(((prelu_out) >> out_negative_shift), 8);
			}else{
					*data = (q7_t) __SSAT(((*data) >> out_positive_shift), 8);				
			}
            data++;
        }
        wt++;
    }

}
```
out_negative_shift：we assume wt product data should shift to match next layer input.
out_positive_shift：we assume data should shift to match next layer input.

**Comment by felix-johnny** [comment]
Closing this ticket as it isn't valid anymore. Sorry about the delay! 
Relu as a standalone operator is not used in most networks and relu now is supported as a fused operator for the TFLu compatible API's (https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis).
