### ISSUE TITLE
RTX Migration guide can be further improved

### ISSUE THREAD

**Issue by chentang16** [ARM-software/CMSIS_5#390]
The "Kernel startup" as one of the incompatibilities and limitations listed on http://arm-software.github.io/CMSIS_5/RTOS2/html/os2MigrationGuide.html is written in a bit confusing way, which can be better clarified as follows:

*Kernel startup
The function osKernelRunning has been deprecated in CMSIS-RTOS v2. "main()" was by default a running thread in CMSIS-RTOS v1 implementations, which is not the case in CMSIS-RTOS v2 anymore. "main()" was a running thread in v1 even without calling corresponding APIs to initialize and start the Kernel explicitly. In v2 the Kernel should be initialized by calling osKernelInitialize() and should be started by calling osKernelStart or skip that part if osKernelRunning indicated that it is already running.
The example code below shows the common Kernel startup in CMSIS-RTOS v2.

The example code is missing in the current doc too.

**Comment by JonatanAntoni** [comment]
@chentang16, May I ask you to cross check the provided fix and finally close this issue, please?

**Comment by ReinhardKeil** [comment]
Closing as there is no further activity
