### ISSUE TITLE
osMessageQueueAttr_t preallocating mq_mem size unituitive

### ISSUE THREAD

**Issue by ablaylock** [ARM-software/CMSIS_5#392]
When preallocating a Message Queue's memory the preallocated memory cannot just be `sizeof(MESSAGE_TYPE)*NUM_MESSAGES` as the source calculates each block as:
`block_size = ((msg_size + 3U) & ~3UL) + sizeof(os_message_t);`
which is obviously larger than just `msg_size` (`sizeof(MESSAGE_TYPE)`). This isn't captured in the documentation and requires source code review to figure out. Additionally one cannot calculate the memory requirement as they do not have access to the definition of `os_message_t`. 

What is the recommended way of calculating the memory requirements of an `osMessageQueue` with a given number of messages (`NUM_MESSAGES`) and size of the message (`sizeof(MESSAGE_TYPE)`)?

**Comment by JonatanAntoni** [comment]
Hi @ablaylock,

for RTX5 you can use the provided macros for size calculation, e.g. [osRtxMessageQueueMemSize](http://arm-software.github.io/CMSIS_5/RTOS2/html/group__rtx5__specific__defines.html#ga47eb1e21f1bf9a42281c6c89c7473e99).

Cheers,
Jonatan

**Comment by ablaylock** [comment]
Thank you
