### ISSUE TITLE
osThreadTerminate when osThreadGetState returns osThreadInactive

### ISSUE THREAD

**Issue by MrReberT** [ARM-software/CMSIS_5#402]
I want to use the function osThreadGetState to check whether it is safe to call osThreadTerminate. What is the difference of the two return values osThreadInactive and osThreadTerminated? Should I call osThreadTerminate when the return value form osThreadGetState is osThreadInactive?

**Comment by RobertRostohar** [comment]
State `osThreadInactive `should indicate a thread that has either not been created or has been destroyed (terminated and resources freed). However `osThreadGetState `might return `osThreadError `instead.

Normally when terminating a thread (executing `osThreadTerminate `or `osThreadExit`) the thread is terminated and its resources are freed. When terminating a thread that is joinable then the thread is terminated but the resources are not freed. This is indicated by the state `osThreadTerminated`. The resources are freed when the thread is detached or joined. 

`osThreadTerminate `can succeed only when thread is active (ready, running, blocked). It will fail when thread is inactive or terminated.

**Comment by MrReberT** [comment]
Ok, I see. Thanks.
