### ISSUE TITLE
Not using Arm ACLE macros

### ISSUE THREAD

**Issue by smeijer1234** [ARM-software/CMSIS_5#417]
Many of the kernels (in the DSP library) have optimised versions for cores that implement the DSP architecture extension. This is checked with #defines like so:

`#if (defined(ARM_MATH_CM7) || defined(ARM_MATH_CM4) ... `

There are several problems with this approach:
- more of a style issue: it unnecessary clutters the code with all these cases,
- but more importantly: it is not very portable or future-proof. 

For example, the Cortex-M33 that can implement the DSP extension, will execute the slow kernel, indicated in the library with:

`/* Run the below code for Cortex-M0 */`

What we should be doing instead, is not checking for particular M core implementation, but the ACLE predefined macros for the required architecture extension. For the DSP extension, that will for example be __ARM_FEATURE_DSP

**Comment by JonatanAntoni** [comment]
Hi @smeijer1234,

Thanks for pointing this out. We have some more similar usability issues on our backlog.

Cheers,
Jonatan

**Comment by christophe0606** [comment]
It is no more the case. No more tests for the cores are done in the code (except for M0 but it is a known issue very limited and will be cleaned soon).

The code is now checking for features.
