### ISSUE TITLE
Pointer Arithmetic

### ISSUE THREAD

**Issue by smeijer1234** [ARM-software/CMSIS_5#420]
Closely related to #419, we should treat loops as loops, and thus also index them as loops. For example, rather than doing the pointer arithmetic like this.

```
    inA2 = *(pSrcA + 1);
    inB2 = *(pSrcB + 1);
    inA3 = *(pSrcA + 2);
    inB3 = *(pSrcB + 2);
    inA4 = *(pSrcA + 3);
    inB4 = *(pSrcB + 3);
```
we should just index the arrays with pSrcA[1], pSrcA[2], pSrcB[3], etc. Not only will this be better for readability, it will assist compilers in doing better/more aggressive analysis/transformations.

**Comment by llefaucheur** [comment]
Hi smeijer1234, indeed like #419 we should look at this code as an intermediate level before translation to assembly. Regards, Laurent.

**Comment by christophe0606** [comment]
What would be the performance impact of doing this change when the code is compiled with gcc or AC5 ?

**Comment by christophe0606** [comment]
We are moving CMSIS-DSP to a new repository : https://github.com/ARM-software/CMSIS-DSP

I have recreated the github issues on the new repository (sometimes merging a few related ones). You can see the link just above this comment (... mentioned this issue ...).

So, I am closing the github issue here.
