### ISSUE TITLE
Negative timer tick

### ISSUE THREAD

**Issue by juliobc** [ARM-software/CMSIS_5#434]
Hi, I saw an unusual behavior of a os timer and I have this in the RTOS window when I am debuging:

![2018-09-21 11_25_14](https://user-images.githubusercontent.com/25198818/45872957-a6bb4b00-bd91-11e8-9e67-2fdb22e8f162.png)

It is possible to have negative numbers?
Thanks

**Comment by juliobc** [comment]
I am sorry, I am working with the last version of RTOS RTX5

**Comment by JonatanAntoni** [comment]
Hi @juliobc,

That looks like an error in Component Viewer on the first glance. Both values, `osRtxTimer_t.tick` and `osRtxTimer_t.load` are defined unsigned. I need to check whether the display accidentally uses signed types instead. In this case large unsigned values would appear as negatives.

Thank you very much for making us aware of that issue. I'll report back soon.

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
Addendum: I quickly glanced over RTX5.scvd (which defines the contents for the component viewer window). The display string for `Tick` and `Load` are both using `%d` format specifier, which is signed integer. As a workaround you could try to change this locally using `%u` specifier instead.

**Comment by JonatanAntoni** [comment]
HI @juliobc,

Unfortunately I got notified by the developers that `%u` is not accepted by MDK. Sorry for that. We need to further investigate where we need to apply the fix.

Cheers,
Jonatan

**Comment by juliobc** [comment]
Hi @JonatanAntoni 
ok. I revert
Thanks

**Comment by JonatanAntoni** [comment]
Hi @juliobc,

we have now traced the issue back into the tool. Hence its not a bug here.
Unfortunately, you need to wait for next release of MDK which will be 5.27.

Cheers,
Jonatan

**Comment by juliobc** [comment]
Ok @JonatanAntoni
thanks.

**Comment by JonatanAntoni** [comment]
Hi @juliobc,

May I ask you to finally check the issue is solved with MDK 5.27, please?
Consider closing this issue if no further discussion required.

Thanks,
Jonatan

**Comment by juliobc** [comment]
Fixed in MDK 5.27

Thanks
