### ISSUE TITLE
Optimized filtering function for half-band filters

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS_5#440]
Half-band filters are a special class of low pass filtering (see [here](https://www.dsprelated.com/showarticle/1113.php)).
As a consequence of this, it happens that almost half of the coefficients are zero.
And so they could be implemented in an optimized way that reduces number of multiplications and sums.

I wonder if DSP library can be extended offering an optimized implementation for this kind of FIR filters.

**Comment by christophe0606** [comment]
I close it since you created the similar issue https://github.com/ARM-software/CMSIS_5/issues/803

**Comment by escherstair** [comment]
I forgot about this issue.
Too much time since any feedback
