### ISSUE TITLE
osKernelSuspend() return

### ISSUE THREAD

**Issue by juliobc** [ARM-software/CMSIS_5#445]
Hi,

Could osKernelSuspend() return 0?

Regards

**Comment by JonatanAntoni** [comment]
Hi @juliobc,

Theoretically, yes. `osKernelSuspend()` returns zero on error for instance. Or if there is any element that's delay has been expired. If you use this call in the context of the idle thread only, I expect it should never return zero.

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
@juliobc, it's highly recommended to check the result value nonetheless. Otherwise you might get strange race conditions. If `osKernelSuspend()` returns zero, you should not put the system to sleep at all.

**Comment by juliobc** [comment]
Hi @JonatanAntoni . Yes I check the result value too.

thanks for the comment
