### ISSUE TITLE
CIFAR-10 Caffemodel Vs CMSIS_5 NN implementation

### ISSUE THREAD

**Issue by sunejas** [ARM-software/CMSIS_5#452]
Hi, i have query regarding differences in the cifar10 caffe model (https://github.com/ARM-software/ML-examples/blob/master/cmsisnn-cifar10/models/cifar10_m7_train_test.prototxt) and the CMSIS_5 NN implementation (https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/arm_nnexamples_cifar10_parameter.h) 

Apart from the maxpool-relu order difference in layer1, which is mathematically ok (#350),  the number output channels of layer2 & layer3 are different, thus causing difference in number of parameters/ops:
![b](https://user-images.githubusercontent.com/15884722/47064159-dd06b180-d1fb-11e8-983f-6ffe406dd89c.png) ![a](https://user-images.githubusercontent.com/15884722/47064164-e1cb6580-d1fb-11e8-9308-b230e8399520.png)

So the CMSIS_5 arm_nnexample_cifar10 code for Cortex-M4 and Cortex-M7  was not generated from the caffemodel provided in ML-examples?
Could you provide the caffemodel which was used for the code generation?

**Comment by felix-johnny** [comment]
Resolved by https://github.com/ARM-software/CMSIS_5/issues/444
