### ISSUE TITLE
Question, can the include files in the exported header be controlled?

### ISSUE THREAD

**Issue by JakkoVerhallen** [ARM-software/CMSIS_5#468]
Hi all,

I've got a question about the generated header file from SVDConv.
Currently, it produces these lines:

#include "core_<cpu name>"
#include "system_<devicename>"

Are these lines hardcoded, or can they be controlled via options?
We'd like to have a single header file for the custom peripherals for two microprocessors, which are not of the same time. So the core inclusion can be done before loading the generated header file.

Perhaps the question does not concern only the file inclusion, but the whole "Processor and Core Peripheral Section" section.

Thanks!
Jakko

**Comment by jkrech** [comment]
Hi Jakko,

the SVDConv generates the device header in a CMSIS-Core compliant way. This means the CMSIS core and system header file inclusion is mandatory and cannot be controlled via the SVDConv command line.

When you state that the microprocessors are not of the same type, I assume that you mean both devices use different processors. In this case this also has an impact on the Processor and Core Peripheral Section.

I would recommend to develop and maintain two separate SVD files and generate a device header from each SVD which is then specific for the device rather than fighting the existing structure.

Regards,

Joachim

**Comment by JakkoVerhallen** [comment]
Hi Joachim,

Thanks for your reply.

It is not more devices, It’s one device with more cores (cm0plus and cm33) which share the same peripheral memory map.
So all non-core related stuff is actually the same.

Unfortunately, our register model database is device related, not core related, so I can only spit out 1 SVD type per device…

“the SVDConv generates the device header in a CMSIS-Core compliant way.”
Does that mean that register description and core description (inclusion) must be in one file? That sounds a bit odd to me, as the custom registers are totally orthogonal to the core.

There is no way to create a core-independent headerfile from the .SVD?
I.m.o. those are 2 different things. In our custom peripherals, there is nothing either CM0plus or CM33 related…

Jakko

**Comment by JakkoVerhallen** [comment]
Hi Joachim, 
Actually, I am asking for a way to split up the header file in 2 parts, a microcontroller-specific part, and a 'all-the-rest' custom part. This would allow for a more modular and reusable system, where we only have to maintain the microprocessor-specific stuff twice, and the all the custom shared stuff once.

Please let me know your thoughts.
Thank you very much!
Jakko

**Comment by jkrech** [comment]
Hi Jakko,
sorry for the delay in response. I think I do understand your view. It's just that I have to admit that SVD has not been designed in that way. Also you will find multi-processor designs out there, where the different processors have a different memory map, where some subsystems, peripherals memories are not accessible to both processors or the address locations are even different. Hence in a common case there is a relationship of "custom data" and a processor. Therefore we have chosen to support the heterogeneous case in CMSIS, where a software project is specific to a single processor's view. 

I have double checked, but there is no way in SVDConv to separate the "processor" from the "peripheral data" dependent files into different header files.
However there is obviously nothing wrong in post-processing and editing the generated files if that's what you required. Also you could generate a single SVD file from your database and prepend the processor specific  sections and then build two device header files that obviously contain redundant data.

SVD does not support include statements, however you could bolt this capability from the outside using a C-Preprocessor from any compiler toolchain.

I am sorry to say, but we don't have a solution at hand, that supports your requirements straight away.

Kind regards,

Joachim

**Comment by JonatanAntoni** [comment]
Closing because we won't be able to fulfill the request in SVDConv. Sorry.
