### ISSUE TITLE
Possible Bug arm_nn_activations_direct_q15

### ISSUE THREAD

**Issue by rarazac** [ARM-software/CMSIS_5#470]
The function arm_nn_activations_direct_q15 has, in my opinion a wrong output.
I think the error comes from using  `__USAT` instead of `__SSAT` and also the interpolation.

If I just use the simpler method and take only one q15 lookup-table value, as the q7 version does:
`out = lookup_table[(uint8_t) (in >> shift_size)];`
The output of this "fixed" q15 version is similar to the q7 and a numpy reference, as shown in following figure:
![tanh](https://user-images.githubusercontent.com/24594953/49011388-82576280-f176-11e8-85fa-4ba703e217db.png)

**Comment by csukuangfj** [comment]
This issue can be reproduced using
https://github.com/ARM-software/CMSIS_5/blob/df4a10b49bc667c055f4c84921f3385cf4518ffd/CMSIS/NN/NN_Lib_Tests/nn_test/arm_nnexamples_nn_test.cpp#L192-L197

`test4[i]` should be 0 whenever `test2[i]` is negative.
