### ISSUE TITLE
Deconvolution layer support in NN library

### ISSUE THREAD

**Issue by kartikmadhira1** [ARM-software/CMSIS_5#472]
I was wondering if the deconvolution layer or the TF equivalent being [conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/layers/conv2d_transpose) is possible to realise using CMSIS library in C. And can we expect to have the support to be added in the future releases if its not there?

**Comment by kartikmadhira1** [comment]
any updates on this?

**Comment by majianjia** [comment]
Is there a plan for transposed convolution currently?
