### ISSUE TITLE
Why does depthwise convolution must have same input and output channel?

### ISSUE THREAD

**Issue by majianjia** [ARM-software/CMSIS_5#481]
In Tensorflow, there is another shape parameter when i create kernel.
Which indicated a multiplier of depthwise convolution. It basicly creates more sets of kernels for depthwise conv. 
If the input channel = 2, multiplier = 2, then the output channel should be 2x2=4. 
This helps me to improve my model. 
https://github.com/ARM-software/CMSIS_5/blob/2efcd747d7cc1c09ab9f5f430139635f611ebcbe/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c#L117

**Comment by woolpeeker** [comment]
So is there any explaination about the equality of ch_im_in and ch_im_out. I feel confused too.
