### ISSUE TITLE
Implementation of CMSIS-Driver

### ISSUE THREAD

**Issue by hackrid** [ARM-software/CMSIS_5#49]
where do you plan to put the implementation of CMSIS-Drivers ?
Some work has already gone into the development of STM32 drivers.
They are included in the "STMicroelectronics STM32F4 Series Device Support, Drivers and Examples" from https://www.keil.com/dd2/pack/

**Comment by JonatanAntoni** [comment]
Each vendor is asked to provide device packs for his own products. A couple of device support packs are maintained by ARM at the moment. Both are available on the link you already provided, or using the Pack Installer delivered with uVision.

**Comment by JonatanAntoni** [comment]
I close this issue due to no further activity.
