### ISSUE TITLE
No library for CM4 without FPU

### ISSUE THREAD

**Issue by danny4478** [ARM-software/CMSIS_5#506]
I got this when building TF-M for CM4:
**_"arm-none-eabi/bin/ld: error: ../TFM/CMSIS_5/CMSIS/RTOS2/RTX/Library/GCC/libRTX_CM4F.a(rtx_system.o) uses VFP register arguments, tfm_ns.axf does not"_**

I assume the F stands for FPU, but there is no .a file for CM4 without an FPU under CMSIS/RTOS2/RTX/Library [GCC/ARMCLANG].

When I use /libRTX_CM3.a the build is successful (but I need CM4).

**Comment by jkrech** [comment]
Due to instruction set compatibility using the CM3 library for Cortex-M4 based devices without FPU is the right thing to do.

**Comment by danny4478** [comment]
Great. Thanks!
