### ISSUE TITLE
RTX5 SCVD Changes Removed Objects listing

### ISSUE THREAD

**Issue by kevingoh** [ARM-software/CMSIS_5#522]
I was having E306 errors when viewing RTX5 with Component Viewer in Keil MDK 5.26, with the SCVD downloaded with CMSIS pack 5.4..then I tried to add the SCVD file in this repository. 

The error is gone but it seems that it was because the latest commit has omitted the objects listing. 

May I know is this kind of temporary workaround? Because it is now hiding meaningful information...

Attaching screenshot from Vim diff on the thread object portion.

BR,
Seng Tak
![rtx5_scvd_diff](https://user-images.githubusercontent.com/4591380/51532326-1d4f7e80-1e40-11e9-9113-043248f7b24f.PNG)

**Comment by kevingoh** [comment]
Hi Vladimir,

Thanks for replying and sorry for not looking close enough.

But in fact the component viewer was not showing running threads…or was it because I am using the SCVD with RTX kernel v5.4?

**Comment by VladimirUmek** [comment]
Yes, this is the reason. The latest RTX5 component view uses different objects IDs, because they were changed recently in RTX5 (see [commit](https://github.com/ARM-software/CMSIS_5/commit/87c33cf147a1c55936401034eb35c33571e053b8).

**Comment by kevingoh** [comment]
Thanks a lot Vladimir, sorry for my ignorance
