### ISSUE TITLE
Incorrect MPU TEX setting for Device non-shared memory

### ISSUE THREAD

**Issue by negative-slack** [ARM-software/CMSIS_5#528]
https://github.com/ARM-software/CMSIS_5/blob/80d36a90b1d4dea76ce8652faa187ca36d006653/CMSIS/Core/Include/mpu_armv7.h#L137

That comment (and the code) is incorrect. It should be:
TEX: 001b (if non-shareable) or 000b (if shareable)

See: https://developer.arm.com/docs/dui0646/latest/cortex-m7-peripherals/optional-memory-protection-unit/mpu-access-permission-attributes#BIHHEDAE

**Comment by JonatanAntoni** [comment]
Hi @negative-slack,

You're partly correct, the comment is wrong. It should state:
`* - TEX: 000b (if shareable) or 010b (if non-shareable)`

But the code seems to be correct.
```
#define ARM_MPU_ACCESS_DEVICE(IsShareable) ((IsShareable) ? 
/*                                    TEX  S   C   B                              TEX    C  B  S   */
/*      shareable: */ ARM_MPU_ACCESS_(0U, 1U, 0U, 1U) : // Table 4.55 Column 2  [ 0b000, 0, 1, x ]
/*  non-shareable: */ ARM_MPU_ACCESS_(2U, 0U, 0U, 0U))  // Table 4.55 Column 14 [ 0b010, 0, 0, x ]
```

Cheers,
Jonatan

**Comment by negative-slack** [comment]
You're right. The table color code in the link I pasted above is misleading. In the following link it is more clear.
http://infocenter.arm.com/help/topic/com.arm.doc.dui0646a/BIHIIJDC.html#BIHHEDAE

**Comment by JonatanAntoni** [comment]
Thanks for double checking this. I'll fix the comment.

**Comment by JonatanAntoni** [comment]
@negative-slack, may I ask you to cross check my fix and close the issue, please?

**Comment by JonatanAntoni** [comment]
Closing due to no further activity.
