### ISSUE TITLE
MPU v7 bug in ARM_MPU_ACCESS_NORMAL macro

### ISSUE THREAD

**Issue by negative-slack** [ARM-software/CMSIS_5#532]
https://github.com/ARM-software/CMSIS_5/blob/26dc9a88a2588ad9c67dac8af44f6127e22f63ed/CMSIS/Core/Include/mpu_armv7.h#L157

Hi, this macro seems to have a bug in the passing of the C bit value down to the ARM_MPU_ACCESS_ macro. A right shift by one is missing thus loosing the value that is passed.
It should be (((InnerCp)>>1) & 1U). Alternatively it is possible to drop the mask as these values should never be bigger than 3.

**Comment by negative-slack** [comment]
FWIW I tested the below patch and eventually managed to get my cache working.
``` C
- #define ARM_MPU_ACCESS_NORMAL(OuterCp, InnerCp, IsShareable) ARM_MPU_ACCESS_((4U | (OuterCp)), IsShareable, ((InnerCp) & 2U), ((InnerCp) & 1U))
+ #define ARM_MPU_ACCESS_NORMAL(OuterCp, InnerCp, IsShareable) ARM_MPU_ACCESS_((4U | (OuterCp)), IsShareable, ((InnerCp) >> 1), ((InnerCp) & 1U))
```

**Comment by JonatanAntoni** [comment]
Hi @negative-slack,

thanks for pointing this out. It looks good to me on the first glance. 
Is there any chance to have a unit test case for that? I'd like to enhance the CoreValidation tests if ever possible in a meaningful way.

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
Hi @negative-slack,

should be fixed now.
Can you please cross check and close?

Thanks,
Jonatan

**Comment by negative-slack** [comment]
Looks good.
Closing.
