### ISSUE TITLE
DSP Lib build projects appear to build only for the M0

### ISSUE THREAD

**Issue by ejd037** [ARM-software/CMSIS_5#547]
Hi,

The ARM project for the DSP library, located in both DSP\Projects\ARM\arm_cortexM_math.uvoptx and in DSP_Lib\Source\ARM\arm_cortexM_math.uvoptx, only contains a project for the Cortex-M0 (uVision only shows a "cortexM0l" target). Where are projects for other cores, in particular the M4F? I'd like to make sure the pre-built library that comes with the wad, Lib/ARM/arm_cortexM4b_math.lib, was actually built to make use of the M4F.

Thanks,

Eric

**Comment by GuentherMartin** [comment]
Hello Eric,

when you open this project with uVision than you can select different targets (Cortex cores) via the target drop down menu.

Martin

**Comment by ejd037** [comment]
Thanks Martin, got it. I'm new to uVision.

**Comment by JonatanAntoni** [comment]
@ejd037, can you close this issue if its solved, please?
