### ISSUE TITLE
Choosing cortex-M3 in iar can compile, but cortex-M4 error

### ISSUE THREAD

**Issue by ccnankai** [ARM-software/CMSIS_5#549]
I have a project running on the arm. For convenience, I extracted the code and deleted the files that were not used on the pc, so that I can compile and run directly on the computer with cmake and gcc. After the code is modified, the project is loaded and compiled with iar. When Cortex-M3 is selected, it can be compiled normally. But when you choose M4, there will be a lot of errors, which are inconsistent with the declaration in iar intrinsics.h.

![1](https://user-images.githubusercontent.com/33537489/54065733-02a25f00-4260-11e9-9f76-f1592bb12c7a.png)

![2](https://user-images.githubusercontent.com/33537489/54065766-4006ec80-4260-11e9-9841-7c029cffafbe.png)
What can I do to avoid this error?

**Comment by JonatanAntoni** [comment]
Hi @ccnankai,

Did you close this issue by purpose?
To me it looks like a clash between files shipped by IAR installation and CMSIS.

Can you give us some more information about the versions you are using?
Perhaps @TTornblom can help as well.

Cheers,
Jonatan

**Comment by TTornblom** [comment]
I assume the problem was not including the target specific include file when changing the device in the IDE.
I would be happy to have a look at the project if this is still a problem.
