### ISSUE TITLE
How to print some parameter?

### ISSUE THREAD

**Issue by ccu1tn** [ARM-software/CMSIS_5#569]
Dear everyone;

In this picture, there are some value like  " Im_in" ," dim_im_in"
![1](https://user-images.githubusercontent.com/43333942/56115471-08454000-5f96-11e9-9e52-d707beb01b02.PNG) 
So. How to print the value Im_in and dim_in_in by c++ from a model (ex. Alexnet model)?
Many thank everyone share

**Comment by majianjia** [comment]
hi, 
I am not entirely sure the "print" in your term.
you should already have these parameters before you can use this function.

Im_in is the pointer to the input image.
 Dim_im_in is the dimension of the input image, the image is default to square shap, so you only need to pass once.

If you want to show image, you might consider other lib. For example, opencv can show an image.

**Comment by ccu1tn** [comment]
Hi @majianjia ;
Thank you so much.
