### ISSUE TITLE
Make CMSIS DSP for Cortex-A9 (Renesas-RZ/A1x)

### ISSUE THREAD

**Issue by ua1arn** [ARM-software/CMSIS_5#580]
Hello. Wee propose little path (author - XGudron GitHub member) for arm_math.h to make possibility of compile CMSIS DSP in part of Fourier transforms. Try to apply this. As next step, build script for Keil MDK can be provided. Today not have enough information about library archives naming conventions.

[cmsis-5.5.1-cortex-a9.zip](https://github.com/ARM-software/CMSIS_5/files/3124319/cmsis-5.5.1-cortex-a9.zip)

**Comment by JonatanAntoni** [comment]
Hi @ua1arn,

Thanks for your contribution. Please bare in mind pull requests are typically easier to handle than zipped patch files.

Cheers,
Jonatan

**Comment by ua1arn** [comment]
Can you add me in collaborators?

 

  _____

**Comment by JonatanAntoni** [comment]
Hi @ua1arn,

This project is open for contributions to everybody. You can create pull requests without any limitation.

Cheers,
Jonatan

**Comment by ua1arn** [comment]
See
https://github.com/ARM-software/CMSIS_5/pull/582

**Comment by christophe0606** [comment]
For reasons explained in https://github.com/ARM-software/CMSIS_5/pull/582#issuecomment-496790999 , we won't merge those changes.

> Wee propose little path (author - XGudron GitHub member) for arm_math.h to make possibility of compile CMSIS DSP in part of Fourier transforms.

Regarding possibility of customizing CMSIS-DSP and only include some parts of it (like only including the FFT tables you use) : it was recently introduced in CMSIS-DSP.

There are now lots of compilation flags to tune what you want to build and include.
There is also a cmake build which is making a bit easier to set those compilation flags. But it can be done without the cmake.
