### ISSUE TITLE
why cmsis_os no define osPoolDelete ?

### ISSUE THREAD

**Issue by Cherish-Gww** [ARM-software/CMSIS_5#585]
When I use cmsis_os.h, and I found there is no define a function named osPoolDelete, that means when your create a Pool it will exist all the time.

**Comment by JonatanAntoni** [comment]
Hi @Cherish-Gww,

Please take not CMSIS-RTOS is deprecated and has been superseded by CMSIS-RTOS2.

Are you actually using `cmsis_os.h` (i.e. CMSIS-RTOS) to adopt another RTOS your own? Or are you using RTX4 (i.e. reference implementation for CMSIS-RTOS).

The latter does not use dynamic memory allocation for memory pools. Hence `osPoolDelete` has never been considered.

Cheers,
Jonatan

**Comment by Cherish-Gww** [comment]
@JonatanAntoni 
Thank you, I use freertos, use CMSIS version 1.02. it is too old for me, and I want use RTOS2, is there have a cmsis_os2.c for freertos?

**Comment by Cherish-Gww** [comment]
@JonatanAntoni 
Oh I found here
https://github.com/ARM-software/CMSIS-FreeRTOS
thank you very much

**Comment by JonatanAntoni** [comment]
Hi @Cherish-Gww,

take a look to [CMSIS-FreeRTOS](https://github.com/ARM-software/CMSIS-FreeRTOS). It is a ready to use packaging of vanilla FreeRTOS with a full functional CMSIS-RTOS2 adoption layer, based on latest CMSIS-RTOS2 API version 2.3.1 and FreeRTOS 10.2.0.

Cheers,
Jonatan

**Comment by Cherish-Gww** [comment]
@JonatanAntoni 
I found this in cmsis_freertos.txt
   - \b osMemoryPoolAlloc: \token{not implemented}
   - \b osMemoryPoolDelete: \token{not implemented}
   - \b osMemoryPoolFree: \token{not implemented}
   - \b osMemoryPoolGetBlockSize: \token{not implemented}
   - \b osMemoryPoolGetCapacity: \token{not implemented}
   - \b osMemoryPoolGetCount: \token{not implemented}
   - \b osMemoryPoolGetName: \token{not implemented}
   - \b osMemoryPoolGetSpace: \token{not implemented}
   - \b osMemoryPoolNew: \token{not implemented}
and I no found osMemoryPoolDelete

**Comment by JonatanAntoni** [comment]
Please move questions regarding CMSIS-FreeRTOS to the according project.

**Comment by ilg-ul** [comment]
> take a look to CMSIS-FreeRTOS. It is a ready to use packaging of vanilla FreeRTOS with a full functional CMSIS-RTOS2 adoption layer, based on latest CMSIS-RTOS2 API version 2.3.1 and FreeRTOS 10.2.0.

this should be a retorical question, but just to be sure, can you confirm that this project passed the CMSIS RTOS validation suite?

**Comment by JonatanAntoni** [comment]
Closing this because it does not belong to CMSIS. Please raise questions regarding CMSIS-FreeRTOS to the according project.
