### ISSUE TITLE
Core_A cmsis_gcc.h uses asm rather than __asm

### ISSUE THREAD

**Issue by dzabawa** [ARM-software/CMSIS_5#593]
The `asm` keyword isn't recognized under -std=c99/c11. I believe this should be using `__asm` as in the corresponding Core include, unless there is another reason for the difference.

**Comment by JonatanAntoni** [comment]
Thanks for pointing this out. Does the provided fix solve your issue?

**Comment by dzabawa** [comment]
perfectly, thanks!
