### ISSUE TITLE
Cmsis compiler errors undefined reference to `arm_convolve_HWC_q7_RGB'

### ISSUE THREAD

**Issue by ccu1tn** [ARM-software/CMSIS_5#594]
Dear everyone

I trying to the compiler arm_nnexamples_cifar10.cpp by mbed. but it appears one error (the error in the picture)
This is the header file and **arm_convolve_HWC_q7_RGB** function defined in **arm_nnfunctions.h** file
![thuvien](https://user-images.githubusercontent.com/43333942/58010654-5b755a00-7b23-11e9-8c6e-d6a3cf4c367c.PNG)
This is error
![mbecafi10](https://user-images.githubusercontent.com/43333942/58010578-354fba00-7b23-11e9-80c2-0885e83fe0b4.PNG)

How to I can fix it?
Many thanks

**Comment by JonatanAntoni** [comment]
Hi @ccu1tn,

The error message tells me that `arm_convolve_HWC_q7_RGB` cannot be linked. The function you try to use is defined in `arm_convolve_HWC_q7_RGB.c`. Are you sure this source file is included for compilation into your mbed project? The output only shows a single source file that is compiled. I guess you need to fix your mbed project setup. In doubt I suggest to get in touch with the mbed team.

Cheers,
Jonatan

**Comment by ccu1tn** [comment]
HI @JonatanAntoni ;
yes, the source file is included for compilation into my mbed project. This is PATH I have configed for mbed.
![config](https://user-images.githubusercontent.com/43333942/58025222-92a93280-7b46-11e9-9670-96b3efbc89f4.PNG)
This is all file in my folder to compile 
![thu](https://user-images.githubusercontent.com/43333942/58025266-aa80b680-7b46-11e9-9fd9-a86faf613fd9.PNG)
 It is only an example, I want to compile convolution functions with mbed.

**Comment by JonatanAntoni** [comment]
I cannot spot `arm_convolve_HWC_q7_RGB.c` in your screenshots. On the screenshots it looks like you have copied all the header files. What about all the sources?
As I stated earlier: To me this looks like a build system issue. From CMSIS point of view I can only tell you that you need to include at least `arm_convolve_HWC_q7_RGB.c` into your project.

**Comment by ccu1tn** [comment]
Dear @JonatanAntoni 

I included all library *.c file in my project, But, It not work. 
This is an error. 
![error  o](https://user-images.githubusercontent.com/43333942/58061889-af775180-7baa-11e9-99ce-d14a04da81a7.PNG)

**Comment by JonatanAntoni** [comment]
Closing because this is a build system issue in the first place. Please get in contact with the mbed community about the build system.

**Comment by ccu1tn** [comment]
Many thank @JonatanAntoni
