### ISSUE TITLE
CMSIS_5 on CORTEX M4 STM32F4xx

### ISSUE THREAD

**Issue by SylvainLaurent37** [ARM-software/CMSIS_5#609]
Hi everyone.

I'm working on STM32 with Keil and i would to use CMSIS_5 and particularly DSP/FFT.
Today I'm developping with an old library.

Does anyone have a template project with Keil using CMSIS_5 ?
Thank you very much for your help and sharing.

**Comment by ReinhardKeil** [comment]
What STM32 device are you using?

**Comment by SylvainLaurent37** [comment]
I'm using an STM32-discovery board with STM32F429ZI.

**Comment by ReinhardKeil** [comment]
When you use the examples that are part of the Keil STM32F4 pack, then the current version of the CMSIS pack is automatically used.

________________________________

**Comment by SylvainLaurent37** [comment]
Thanks for your response.
I use an RLink debugger and I would convert µVision project to Ride7 project.
When I try to build the project : "cc1.exe: fatal error: armv7e-m/fpu: No such file or directory"

**Comment by ReinhardKeil** [comment]
Well the error message is not descriptive enough to understand the problem (which is most likely in the import step).

Did you check that the project builds under MDK?
________________________________

**Comment by ReinhardKeil** [comment]
Closing as there is no further follow up.
