### ISSUE TITLE
arm_nnfunctions.h signed and unsigned comparison

### ISSUE THREAD

**Issue by fgr1986** [ARM-software/CMSIS_5#618]
Hi, the file `https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/Include/arm_nnfunctions.h`  generates a GCC [-Werror=sign-compare] Warning/Error with gcc-arm-none-eabi/7-2018q2
Thank you very much!

**Comment by felix-johnny** [comment]
Fixed.
