### ISSUE TITLE
Library issues with SVDConv.linux

### ISSUE THREAD

**Issue by jmcfarlan** [ARM-software/CMSIS_5#63]
When trying to use the SVDConv.linux in our environment, we get the following:

./SVDConv.linux: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./SVDConv.linux)
./SVDConv.linux: /tools/cadence/incisiv/14.20.006/tools/lib/64bit/libstdc++.so.6: version`GLIBCXX_3.4.15' not found (required by ./SVDConv.linux)

It seems that our environment in stuck at RedHat 6.x which limits us to GLIBC_2.12.  Is there any way to modify the path that this utility searches for to find the libraries?

**Comment by jkrech** [comment]
Could you please download the SVDConv Linux build using GCC 4.4.4 from here and let me know whether this would work for you?

www.keil-compiler.de/Transfer/Preview/SVDConv_gcc-4.4.4.zip

Redirecting an executable to search for shared libraries in other folders can be done using the environment variable LD_LIBRARY_PATH

To find out which requirements a library has you can run objdump -p <program>

**Comment by jmcfarlan** [comment]
I downloaded the 4.4.4 version and it is closer to working.  I can run with the following to options:

  - SVDConv myDevice.svd
  - SVDConv myDevice.svd --generate=partition

However, when I run the following I get "Segmentation fault (core dumped)"

  - SVDConv myDevice.svd --generate=header

**Comment by thorstendb-ARM** [comment]
Hi,
can you please attach a (small) reproducer SVD file?
Thanks!

**Comment by jmcfarlan** [comment]
I am having trouble getting a smaller testcase to show the same issue.  As another data point, the svd file converts fine on the PC side using V2.86g.

Our IT folks also asked about the chances of obtaining the source code so we could compile locally on our platform.

**Comment by JonatanAntoni** [comment]
@jmcfarlan Does this issue still exists with current SVDConv 3.3.1? Please review, report back or close this issue if solved, please.

**Comment by jmcfarlan** [comment]
The new version fixes my issues.
Thanks.
