### ISSUE TITLE
How to calculate Q format number:

### ISSUE THREAD

**Issue by Haryslee** [ARM-software/CMSIS_5#646]
input Qm.n,
output Qm.n,
weight Qm.n,
bias Qm.n
Could you please tell me the detail? I am so confused.

**Comment by christophe0606** [comment]
@Haryslee You may find [this link](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/converting-a-neural-network-for-arm-cortex-m-with-cmsis-nn) useful

**Comment by Haryslee** [comment]
> @Haryslee You may find [this link](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/converting-a-neural-network-for-arm-cortex-m-with-cmsis-nn) useful

@christophe0606 Thanks a lot.
