### ISSUE TITLE
git lfs pull does not work

### ISSUE THREAD

**Issue by Ruide** [ARM-software/CMSIS_5#666]
I am using ubuntu 16.04 on win10 wsl 2. 

When i git clone with git lfs installed, i get the following error:
"This repository is over its data quota. Purchase more data packs to restore access."

Then i use trace to see what happens and get the following:
...(skipped)
17:45:14.700595 trace git-lfs: fetch CMSIS/Utilities/Win32/SVDConv.exe [14f40abd8803a863b7447c957643260f81f5968a2a7c0d32304d558cb2944f52]
17:45:15.085524 trace git-lfs: HTTP: 403
17:45:15.087452 trace git-lfs: HTTP: {"message":"This repository is over its data quota. Purchase more data packs to restore access.","documentation_url":"https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/"}
17:45:15.092545 trace git-lfs: api error: This repository is over its data quota. Purchase more data packs to restore access.

Can anyone help with me? Did I do anything wrong?

Thank you!
Ruide

**Comment by JonatanAntoni** [comment]
Hi Ruide,

sorry for that inconvenience. Its a known issue caused by traffic limitation at GitHub.
Please try it again, we extended the traffic quota.

Cheers,
Jonatan

**Comment by Ruide** [comment]
> Hi Ruide,
> 
> sorry for that inconvenience. Its a known issue caused by traffic limitation at GitHub.
> Please try it again, we extended the traffic quota.
> 
> Cheers,
> Jonatan

Yep, it works now. Thanks for your help!

Ruide
