### ISSUE TITLE
arm_sqrt_f32 file could not be found

### ISSUE THREAD

**Issue by MishalJasmine** [ARM-software/CMSIS_5#669]
Hi,

I am currently working on CMSIS DSP. In the file arm_math.h, a function arm_sqrt_f32 is defined and it in turn uses a function sqrtf. I am not able to find the file arm_sqrt_f32.h. Eclipse keeps throwing an error at the function sqrtf. 

In function `arm_sqrt_f32':
C:\CMSIS\ARM\CMSIS\5.6.0\CMSIS\Include/arm_math.h:5870: undefined reference to `sqrtf'

Can I get some help on this?

**Comment by christophe0606** [comment]
Hi,

Which compiler are you using ?

**Comment by MishalJasmine** [comment]
Hi,

I am using Cross ARM GNU C compiler.

**Comment by christophe0606** [comment]
Normally sqrtf should be defined in the gcc libraries.
Is your error a link error or a compile error ? If link error, check the libraries on the gcc command line. -lm for instance.

**Comment by MishalJasmine** [comment]
It is a linker issue. I have added arm_cortexM4l_math and GCC library path. But I still get this error. I also see there are some linker issues in CMSIS_pack 5.6.0. Is it because of that? My target device is MAX32660.

**Comment by christophe0606** [comment]
Are you using -lm to link ? I think the missing sqrtf should be in the standard math library provided with the compiler.

**Comment by MishalJasmine** [comment]
I am sure about -lm. I am using Eclipse and I have added the paths and the standard math library.  

![image](https://user-images.githubusercontent.com/51846137/64151187-70ae9400-ce47-11e9-9a69-ca8a1c9f71d8.png)

**Comment by MishalJasmine** [comment]
Paths to the compiler are automatically added when the CMSIS packs are installed. But the GCC paths and the standard math library paths need to added manually.

**Comment by christophe0606** [comment]
I am sorry I can't really help more. I am sure your issue is related to some linking options.

**Comment by MishalJasmine** [comment]
oh..thats fine..thank you @christophe0606 :-)

**Comment by GuentherMartin** [comment]
Hello MishalJasmine,
you must link the math library (libm). Add '-lm' to your linker stage.

**Comment by MishalJasmine** [comment]
I added the math library using -lm. It looks something like this. 

make all 
Building target: Demo.elf
Invoking: Cross ARM GNU C Linker
arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mlittle-endian -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g3 -Wl,-Map,"Demo.map" -u _printf_float -L C:\Users\Mishal\CMSIS_5\CMSIS\DSP\Lib\GCC -lm libarm_cortexM4l_math.a

But despite of giving the path to the math library it gives this error.
arm-none-eabi-gcc.exe: error: libarm_cortexM4l_math.a: No such file or directory
make: *** [Demo.elf] Error 1

**Comment by JonatanAntoni** [comment]
Hi @MishalJasmine,

Did you write that compiler/linker command line yourself? It looks a bit strange to me. You simply give a file `libarm_cortexM4l_math.a` as input. There are no other `.o` files as input and no `-o <output>` options given. 

The error message simply tells me that no file `libarm_cortexM4l_math.a` can be found in the current directory. You need to give the full path to the file or use `-larm_cortexM4l_math` instead. The latter will instruct the linker to lookup a file named `libarm_cortexM4l_math.a` in all the library search directories.

Cheers,
Jonatan

**Comment by MishalJasmine** [comment]
I didn't write command line. It is automatically generated by Eclipse. I need to add the respective file names and the path in the project properties section and it generates the Makefile for the same.

**Comment by JonatanAntoni** [comment]
Please consider the Eclipse user group for getting detailed help about project configuration.

**Comment by MishalJasmine** [comment]
-L C:\Users\Mishal\AppData\Local\Arm\Packs\ARM\CMSIS\5.5.1\CMSIS\DSP\Lib\GCC\libarm_cortexM4l_math.a

I was get able to get rid of the error with this. 

Thank you
