### ISSUE TITLE
After stm32 internal flash program,system enters osRtxErrorNotify function

### ISSUE THREAD

**Issue by Pupil2013** [ARM-software/CMSIS_5#683]
I am using stm32f405,when save data to internal flash,after program the data to flash,rtx enter osRtxErrorNotify function,stay in the osRtxErrorStackUnderflow case.
Is the flash write operation affect the rtos running?

**Comment by Pupil2013** [comment]
Before the error happens ,there are still about 10k global dynamic memory left.

**Comment by JonatanAntoni** [comment]
Hi @Pupil2013,

`osRtxErrorStackUnderflow` means that the thread running has exceeded its allocated stack. Stack size in RTX5 is not adopted, dynamically. So the free global dynamic memory doesn't affect the stack. 

You can try to enable the stack usage watermarking in RTX5. Than increase the stack size of the faulting thread. Run your application and watch the watermark to discover the actual stack requirements.

Does that help?

Cheers,
Jonatan

**Comment by Pupil2013** [comment]
Thanks&nbsp;Jonatan.
It realy help.I forget to change the thread stack size when debuging.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonatan Antoni"<notifications@github.com&gt;; 
发送时间: 2019年9月16日(星期一) 晚上6:24
收件人: "ARM-software/CMSIS_5"<CMSIS_5@noreply.github.com&gt;; 
抄送: "追忆"<925921351@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ARM-software/CMSIS_5] After stm32 internal flash program,system enters osRtxErrorNotify function (#683)




Hi @Pupil2013,
 
osRtxErrorStackUnderflow means that the thread running has exceeded its allocated stack. Stack size in RTX5 is not adopted, dynamically. So the free global dynamic memory doesn't affect the stack.
 
You can try to enable the stack usage watermarking in RTX5. Than increase the stack size of the faulting thread. Run your application and watch the watermark to discover the actual stack requirements.
 
Does that help?
 
Cheers,
 Jonatan

**Comment by JonatanAntoni** [comment]
Please consider closing this issue if your question has been solved, finally.
