### ISSUE TITLE
bug in arm_nn_mul_q15 with negative numbers and output shift

### ISSUE THREAD

**Issue by antofara** [ARM-software/CMSIS_5#684]
I am working with gcc compiler, I have tried with different optimization options but the following problem still remains.
in function arm_nn_mul_q15, if the result of a multiplication is negative, then applying the outshift generates a wrong, positive, value, because the shift does not consider the number as signed but as unsigned.
dummy example:
[-24576] x [1] with 2 bits of output shift:
expected result [-6144] but actual result a completely different positive number.
The reason behind that is, as I can see after some debugging, that the compiler interprets 
`(q31_t) anything+NN_ROUND(outshift)` as an unsigned, and thus rightshifting does not keep the sign.

I have tried the following workarounds that seems to work for me:
1: change parenthesis order to let the compiler know we are talking about a signed number:
`    *pDst++ = (q15_t) __SSAT((((q31_t) (*pSrcA++) * (*pSrcB++) + NN_ROUND(out_shift)) >> out_shift), 16);`
has to be changed to:
`    *pDst++ = (q15_t) __SSAT(((q31_t) ( (*pSrcA++) * (*pSrcB++) + NN_ROUND(out_shift) ) >> out_shift), 16);`
similar situation for the M4-M7 version
2: use a temporary q31_t accumulator and then use it inside __SSAT

Not sure whether this problem happens also with other compilers.

**Comment by felix-johnny** [comment]
https://github.com/ARM-software/CMSIS_5/commit/e409b45096e7ce7ffaa91b7cfa148af17e84cca5 resolves this issue.
