### ISSUE TITLE
Adding a note that arm_rfft_fast_f32() cannot be performed in-place

### ISSUE THREAD

**Issue by critBit95** [ARM-software/CMSIS_5#685]
Calling the `arm_rfft_fast_f32()` with the same pointer to the input and output buffer produces an invalid, and quite confusing result.

The peaks resulting from mistakenly calling FFT operation on sine wave with frequency on the lower half of the spectrum seem to mirror around the middle of the buffer, suggesting that the invalid results are caused by some other factors (eg. invalid sampling rate). This might be very confusing.

Looking for resolve, I came upon this issue that finally helped me solve it:
https://community.arm.com/developer/tools-software/tools/f/armds-forum/6243/problem-with-arm_rfft_fast_f32

I think it might be worth adding a note in the documentation, that calling FFT operations must not be done in-place (using the same source and destination buffer).

**Comment by christophe0606** [comment]
@critBit95 Thanks for reporting this issue. We will update the documentation.
