### ISSUE TITLE
Error in a comment of cascade of filters

### ISSUE THREAD

**Issue by clamar01** [ARM-software/CMSIS_5#694]
In [arm_biquad_cascade_df2T_f32.c (line 152)](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c#L152)
`/* The current stage input is given as the output to the next stage */`
should be
`/* The current stage output is given as the input to the next stage */`
since it is a cascade of filters.

The same comment is present in [arm_biquad_cascade_df2T_f64.c](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c) and in [arm_biquad_cascade_stereo_df2T_f32.c](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c).

Best regards

**Comment by christophe0606** [comment]
Corrected in commit https://github.com/ARM-software/CMSIS_5/commit/df209ecb0006025ae3adc9f64991f98a23f51f61
