### ISSUE TITLE
RTX: to start or not to start?

### ISSUE THREAD

**Issue by tobermory** [ARM-software/CMSIS_5#718]
This isn't a bug per se, just more a frustration on my part...

Have used RTX4, now switching to RTX5. My toolchain of choice is arm-none-eabi-gcc.  In RTX4, the RTX kernel was pre-set up, with both Initialize and Start already called before main(). main() actually ran as first thread.  Now I see in RTX5, main() is no longer a pre-started thread, and app developer does all the set-up, e.g. the Code Example at

 https://www.keil.com/pack/doc/CMSIS/RTOS2/html/genRTOS2IF.html#usingOS2

I'm fine with this change, in fact I prefer this way of doing things. But was looking through the RTX5 sources recently and found this in rtx_lib.c

#elif defined(__GNUC__)
__WEAK void software_init_hook (void) {
  (void)osKernelInitialize();
}
#endif

This fact isn't called out in the docs anywhere, at least not that I can see. So, if using GCC, which I do, you get HALF a kernel set up?? The software_init_hook is called early in libc, BEFORE main(). Yes, I know it's WEAK so can be overridden, presumably to be empty, by the application, but why is the code there at all?  I'm fine with knowing kernel is alive before main() (RTX4) or knowing kernel isn't alive before main() (RTX5), but it's confusing to learn that RTX5 is sort of halfway kernel setup, at least with GCC.

**Comment by RobertRostohar** [comment]
The reason for initializing the RTX kernel early before main is to support the C library multithreading. C library calls certain mutex functions before main and requires that the kernel is at least initialized (does not need to be running).

The C library multithreading support is currently only implemented for ARM compiler and C library. However the initialization hook to initialize kernel is also provided for GCC.

Yes, this detail is not described in the documentation.

However the RTX kernel initialization (function osKernelInitialize) is only initializing memory objects and has no other side-effects. It can be safely called from main() and the user should normally not need to be aware that it was already called in pre-main.

The actual RTX kernel setup (SVC, PendSV, SysTick) and startup occurs when calling osKernelStart.
