### ISSUE TITLE
Library archives of CMSIS 5.6.0 

### ISSUE THREAD

**Issue by maxvankessel** [ARM-software/CMSIS_5#732]
I've downloaded 5.6.0 release tarbal. 
And tried to use the *.a files, and got:. 
`libarm_cortexM4lf_math.a: file format not recognized; treating as linker script`

I've run `file` on it:
`file libarm_cortexM4lf_math.a libarm_cortexM4lf_math.a: ASCII text`

The content of all archives is only 132Mb, and do not correspond to the contents of the tree
Reading as ascii supplies me with the following info:
```
version https://git-lfs.github.com/spec/v1
oid sha256:8ea78dc0a463f4c5d196887c1a36ce8d5ff141e9ffcded4ad1a50a22c72f6e9d
size 5359640
```
Is this intended?

**Comment by JonatanAntoni** [comment]
Hi @maxvankessel,

The binary artifacts are stored in Git LFS. It looks like downloading the repo to tarball doesn't properly include the external files. I doubt we can do much about it from repository point of view. 

You might want to try to get in touch with GitHub support as this might be addressed on a global scope.

Cheers,
Jonatan
