### ISSUE TITLE
Will CMSIS DSP/NN lib support ARMv8.1-M Architecture?

### ISSUE THREAD

**Issue by tsaiyenting** [ARM-software/CMSIS_5#758]
Hi,
Since Armv8.1-M Architecture might have significant performance uplift for machine learning and digital signal processing applications, will CMSIS DSP/NN library have AarmV8.1-M version?

Regards

**Comment by christophe0606** [comment]
@tsaiyenting It is already the case and we are uploading new 8.1M implementations of the algorithms periodically.
It is of course a work in progress.

**Comment by tsaiyenting** [comment]
Thanks for your reply.
Excuse me for asking: Is there an expected schedule?

**Comment by christophe0606** [comment]
@tsaiyenting We do as quickly as we can. Today we have (for DSP) most of the functions. FilteringFunctions  are not yet finished.
TransformFunctions will come next.

**Comment by tsaiyenting** [comment]
Thanks for your reply.
Look forward to your update :)
