### ISSUE TITLE
Under-sized state buffer for FIRQ15 test

### ISSUE THREAD

**Issue by stephanosio** [ARM-software/CMSIS_5#786]
The state buffer for the `FIRQ15` test is under-sized.

https://github.com/ARM-software/CMSIS_5/blob/73ed0410119f500ec5025c79c04f46379c46620e/CMSIS/DSP/Testing/Source/Tests/FIRQ15.cpp#L126

For instance, when executing the following test sample, the minimum required state buffer size is 41 bytes:
https://github.com/ARM-software/CMSIS_5/blob/73ed0410119f500ec5025c79c04f46379c46620e/CMSIS/DSP/Testing/Patterns/DSP/Filtering/FIR/FIRQ15/FirConfigs1_s16.txt#L251-L254

https://github.com/ARM-software/CMSIS_5/blob/c4c3480075295f226774bf134c00e91441aef1aa/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c#L103

**Comment by stephanosio** [comment]
cc @christophe0606

**Comment by stephanosio** [comment]
In addition, the following comment is not correct because the minimum state buffer size when `ARM_MATH_DSP` is enabled is `blockSize + numTaps`:

https://github.com/ARM-software/CMSIS_5/blob/73ed0410119f500ec5025c79c04f46379c46620e/CMSIS/DSP/Testing/Source/Tests/FIRQ15.cpp#L123-L125

**Comment by stephanosio** [comment]
The same problem exists in `FIRQ7`, `FIRQ31` and `FIRF32` tests as well.

**Comment by christophe0606** [comment]
It should be solved with commit 1d1d70e2385b7c8c31292669713270b7bb378052
