### ISSUE TITLE
understanding osRtxErrorClibSpace

### ISSUE THREAD

**Issue by juliobc** [ARM-software/CMSIS_5#791]
Hi,

I would like to understand a bit more about osRtxErrorClibSpace. I have that error in my code.
The info I found is:
"This error identifier is used with osRtxErrorNotify when RTX5 detects usage of libspace but not enough memory was reserved using OS_THREAD_LIBSPACE_NUM. "
thank you very much.

**Comment by RobertRostohar** [comment]
The definition OS_THREAD_LIBSPACE_NUM specifies the number of threads which use C libspace and is used to reserve space in R/W memory.

libspace holds the static data for the C libraries per thread:
- errno
- floating point status, if floating point is being used
- pointer to heap, used by malloc related functions
- current locale settings

Typically a thread will need libspace if it uses any of the listed items above.

The default value for OS_THREAD_LIBSPACE_NUM is 4, unless thread specific memory allocation is used.

You should increase the OS_THREAD_LIBSPACE_NUM definition if you encounter osRtxErrorClibSpace error.

**Comment by juliobc** [comment]
thank you
