### ISSUE TITLE
osMessageQueue api problem

### ISSUE THREAD

**Issue by iauther** [ARM-software/CMSIS_5#794]
While I use `osMessageQueuePut` in ISR at a high frequency for a long time(where I use a knob key to test), I always get a `HardFault_Handler` error，the following is the test code：

```
typedef struct {
    osMessageQueueId_t  mq;
    osMemoryPoolId_t    mp;
    osEventFlagsId_t    ef;
    osMutexId_t         mtx;
    u8                  ack;
    int                 msg_size;
} msg_t;

static int msg_put(msg_t *m, void *ptr, int len)
{
    void *p;

    osStatus_t st;
    p = osMemoryPoolAlloc(m->mp, 0);
    if(!p) {
        return -1;
    }
    
    memcpy(p, ptr, len);
    st = osMessageQueuePut(m->mq, &p, 0, 0);
    if(st!=osOK) {
        return -1;
    }
    return 0;
}

msg_t* msg_init(int max, int msg_size)
{
    msg_t *m=NULL;
    
    m = (msg_t*)calloc(1, sizeof(msg_t));
    if(!m) {
        return NULL;
    }

    m->mq = osMessageQueueNew(max, sizeof(void*), NULL);
    m->mp = osMemoryPoolNew(max, msg_size, NULL);
    m->ef = osEventFlagsNew(NULL);
    m->ack = 0;
    m->msg_size = msg_size;

    return m;
}

int msg_post(msg_t *m, void *ptr, int len)
{
    int r=0;

    if(!m || !ptr || !len || len>m->msg_size) {
        return -1;
    }

    r = msg_put(m, ptr, len);

    return r;
}


int msg_recv(msg_t *m, void *ptr, int len)
{
    int r=0;
    void *p=NULL;

    if(!m || !ptr || !len || len<m->msg_size) {
        return -1;
    }

    osStatus_t st;
    st = osMessageQueueGet(m->mq, &p, NULL, osWaitForever);
    if(st!=osOK || !p) {
        return -1;
    }
    
    memcpy(ptr, p, m->msg_size);
    osMemoryPoolFree(m->mp, p);

    return r;
}

////////////////////////////////
static msg_t *msg=NULL;
void uart_rx_cb(u8 *data, u16 data_len)
{
    int r;
    key_t k;
    evt_t e;
    
    //...
    //data convert
    
    e.evt = EVT_KEY;
    e.key = k;
    r = msg_post(msg, &e, sizeof(e));
    if(r==0) {
        //...
    }
}


void gui_task(void *arg)
{
    int r;
    evt_t e;
    osStatus_t st;

    msg = msg_init(10, sizeof(e));
    if(!msg) {
        return;
    }

    while(1) {
        r = msg_recv(msg, &e, sizeof(e));
        if(r==0) {
            switch(e.evt) {
                case EVT_KEY:
                {
                    //do nothing
                }
                break;
            }
        }
    }

    msg_free(&msg);
}

int main(void)
{
    ...
    
    osThreadNew(gui_task, NULL, NULL);
    ...
    while(1);
}
```

TIP：the `uart_rx_cb()` called frequency is about 10~20 times/ms

when the fault occur，the caller is `__svcMessageQueueGet()`.  when I use timer to trigger, all is ok.

Anyone have this problem？or my code has some wrong？

Changed the trigger by usb or  spi, I get the same result(fault error), the driver I used is stm32 driver library. I don't think that it's the driver bug.

thanks

**Comment by JonatanAntoni** [comment]
Hi @iauther,

I'd say an HardFault should never happen. I could imagine that sending 10 to 20 messages to your message queue per millisecond could overrun the queue. But this depends on specific details of your device, i.e. system core clock. Without having more details about your application its hard to say. I'd be surprised if the Hard Fault is triggered from within `__svcMessageQueueGet()`. 

Which type of development environment do you use? Using MDK I'd suggest to add Event Recorder to your application. This way you could get some insights whats going on without affecting the timing behavior of your application too much (i.e. compared with a debugger and breakpoints). Another option would be using the System Viewer windows which offers some sort of RTOS awareness. Does it happen that your message queue or memory pool is full? 

Please take special note that interacting with RTOS objects from ISR context there is a post-processing queue involved, see https://arm-software.github.io/CMSIS_5/RTOS2/html/theory_of_operation.html#CMSIS_RTOS_ISR_Calls. This queue needs to be configured properly to your needs, see https://arm-software.github.io/CMSIS_5/RTOS2/html/config_rtx5.html#systemConfig_isr_fifo.

Cheers,
Jonatan
