### ISSUE TITLE
Use of export "C"

### ISSUE THREAD

**Issue by CurtisAMU** [ARM-software/CMSIS_5#824]
While cmsis_os2.h and some RTX headers (e.g. rtx_os.h) contain the
#ifdef  __cplusplus
extern "C"
{
#endif
idiom, others do not. We're using CMSIS-RTOS2 in C++ projects where _export "C"_ in os_tick.h is required.
I think, it would be consistent to include export "C" in all header files that may be included by CMSIS users.

**Comment by JonatanAntoni** [comment]
Hi @CurtisAMU,

thanks for pointing this out. You're right and we are going to add the `extern "C"` declaration to `os_tick.h`.
Please take care to compile the RTX source code itself in C mode (not C++).

Cheers,
Jonatan

**Comment by RobertRostohar** [comment]
extern "C" has been added as requested.

**Comment by JonatanAntoni** [comment]
@CurtisAMU, may I ask you to check the fix and close the issue, please?

**Comment by CurtisAMU** [comment]
Thank you. I checked the fix and it works.
