### ISSUE TITLE
svd schema 1.3 : nvicpriobitstype is defined but not used in the element definition

### ISSUE THREAD

**Issue by Jegeva** [ARM-software/CMSIS_5#856]
it's all in the title :

nvicpriobitstype is defined but not used in the element definition

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified" version="1.3">
...
 
  <xs:simpleType name="nvicPrioBitsType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="2"/>
      <xs:maxInclusive value="8"/>
    </xs:restriction>
  </xs:simpleType>

...

 <xs:complexType name="cpuType">
...
      
      
      <xs:element name="nvicPrioBits" type="scaledNonNegativeInteger"/>

**Comment by jkrech** [comment]
Good catch. We shall remove the type definition as it is a left-over. We have decided to not mandate decimal notation but also allow hex and other number formats as with any other numerical entry in SVD. Note that the SVDConv is checking that this value is in the required range:

*** ERROR M327: ARM_Example.svd (Line 55)
  NVIC Prio Bits not set or wrong value, must be 2..8. Using default (4)
