### ISSUE TITLE
CMSIS-Drivers: Headers are not C++ safe

### ISSUE THREAD

**Issue by ilg-ul** [ARM-software/CMSIS_5#86]
https://github.com/ARM-software/CMSIS/issues/101

**Comment by ReinhardKeil** [comment]
Actually the files work for C++ (at least we have not seen issues with it). However we are going to add the "extern C" guards.

**Comment by RobertRostohar** [comment]
C++ guard macros have been added (dcc903b).

**Comment by ilg-ul** [comment]
great!
