### ISSUE TITLE
unaligned 4 bytes access is replaced by memcpy, adds too much overhead

### ISSUE THREAD

**Issue by RockySong** [ARM-software/CMSIS_5#861]
"__SIMD32" was replaced by "arm_nn_read_q15x2_ia" in order to read 4 bytes from unaligned address. Though this guarantees no unaligned fault due to generated LDRD/LDM instructions in ac6 (ac5 does not), its implementation is memcpy() which adds too much overhead.
In fact most use cases can accept unaligned access, suggest to create a new configuration that determines whether to allow unaligned access and reminds user to enable it if they want better performance.

**Comment by felix-johnny** [comment]
@RockySong  Sorry for the delay. Was it with GCC or ARMC6 that you observe the overhead? We did have some reports of overhead using the memcpy(https://github.com/tensorflow/tensorflow/issues/37361) ..Do you see it without -fno-builtin ?

**Comment by felix-johnny** [comment]
And this is the background to the issue https://github.com/ARM-software/CMSIS_5/issues/546

**Comment by RockySong** [comment]
I see a call to aeabi memcpy

**Comment by felix-johnny** [comment]
@RockySong Not sure that clarifies the question. Have you tied without the  -fno-builtin option? I believe that should resolve the issue that you see.

**Comment by felix-johnny** [comment]
I am closing this issue and if your issue is not resolved after using -fno-builtin , please re open it.
