### ISSUE TITLE
Does CMSIS-DAP support the float64 matrix operations?

### ISSUE THREAD

**Issue by WangShanpeng** [ARM-software/CMSIS_5#866]
https://github.com/ARM-software/CMSIS_5/tree/master/CMSIS/DSP/Source/MatrixFunctions
I see that there are only `arm_mat_mult_f32`, `arm_mat_add_f32` functions in the source code. 
Does CMSIS-DAP support the float64 matrix operations?

**Comment by christophe0606** [comment]
We have started to add float64 versions of the functions but right now for matrix there is only the inverse.

**Comment by WangShanpeng** [comment]
> We have started to add float64 versions of the functions but right now for matrix there is only the inverse.

Thanks very much for your reply. I would like to know how soon the float64 version will be released?

**Comment by christophe0606** [comment]
I unfortunately don't know.

**Comment by WangShanpeng** [comment]
@christophe0606 OK, thank you!
