### ISSUE TITLE
SVDConv does not generate Msk and Pos macros

### ISSUE THREAD

**Issue by vitkorob** [ARM-software/CMSIS_5#867]
If a register is defined as array (with [%s]) the SVDConv does not generate macros for bitfields (*_Pos and *_Msk).

**Comment by thorstendb-ARM** [comment]
Hi,
which version are you using? SVDConv v3.3.35 should fix the issue.
Can you provide an example?

**Comment by vitkorob** [comment]
I used v3.3.27.

Now I have tested v3.3.35 that's ok. Thank you!
