### ISSUE TITLE
RTOSv2 os_Info not initialized with correct values (gcc)

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#87]
I have tried to write a program for STM32F746 using System Workbench for STM32 (gcc)

A call of
`osKernelInitialize();`
fails (-1)

The reason is, that os_Info is not initialized with valid content.

I attach the project

Using uVision the program works without any problem

[RTOSv2test.zip](https://github.com/ARM-software/CMSIS_5/files/507779/RTOSv2test.zip)

**Comment by RobertRostohar** [comment]
os_Info is put into a special section ".os.data".

When using gcc the linker script needs to be updated. Add the following into ".data:" after `*(.data*)`:
`*(.data*)`
`*(.os.data*)`
`*(.os.object*)`

**Comment by RobertRostohar** [comment]
Sections have now been renamed to start with ".bss" /  ".data" which should work with default gcc linker scripts.

**Comment by ReinhardKeil** [comment]
closing issue as it appears to be resolved.
