### ISSUE TITLE
CMSIS-CORE: standardized access to fields with scattered bits

### ISSUE THREAD

**Issue by franzhollerer-Artesyn** [ARM-software/CMSIS_5#88]
This is a feature request for the CMSIS standardization.

The macros _VAL2FLD() and _FLD2VAL() are a great deal to work with fields which are stored in adjacent bits within a register.

I would like a similar standardization for fields which are scattered within a register. For example, consider that a device specific CMSIS header file provided by the chip vendor brings in the following definitions:

``` c
#define TIM_CCMR1_OC1M_Pos       (4U)                                         
#define TIM_CCMR1_OC1M_Msk      (0x007U << TIM_CCMR1_OC1M_Pos)  // low bits of OC1M
#define TIM_CCMR1_OC1MH_Pos     (16U)
#define TIM_CCMR1_OC1MH_Msk    (1U << TIM_CCMR1_OC1MH_Pos)       // high bit of OC1M
```

to describe the this register layout:

![tim_ccmr1_oc1m](https://cloud.githubusercontent.com/assets/17589408/19230950/9a02cd24-8ed7-11e6-9b9a-28d4d4221153.PNG)

It would be great if the vendor specific CMSIS file has to provide TIM_CCMR1_OC1M_VAL2FLD() and TIM_CCMR1_OC1M_FLD2VAL() macros to access the scattered field.

``` c
#define TIM_CCMR1_OC1M_VAL2FLD(val) \
    _VAL2FLD(TIM_CCMR1_OC1MH, (val) & 0x8) | _VAL2FLD(TIM_CCMR1_OC1M, (val) & 0x07)

#define TIM_CCMR1_OC1M_FLD2VAL(reg) .......

```

**Comment by ReinhardKeil** [comment]
While we accept that this is a problem, we have not found a clever way to solve it.
