### ISSUE TITLE
Caffe model used for CMSIS-NN GRU example missing

### ISSUE THREAD

**Issue by seemakumar8** [ARM-software/CMSIS_5#882]
Hi,

Is it possible to provide the caffe model (.protext and .caffemodel) for "CMSIS/NN/Examples/ARM/arm_nn_examples/gru/", similar to the one provided for cifar10 example under https://github.com/ARM-software/ML-examples/tree/master/cmsisnn-cifar10/models

I understand there was random data used to generate the arm_nnexamples_gru_test_data.h. I just want to use a trained model as input, caffe or Tensorflow. 

Thanks

**Comment by felix-johnny** [comment]
@seemakumar8 I am sorry, but those pre-TFLu (https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis) parts are in maintenance mode and no new updates are planned. 
  But, let me check if anyone still has the model and get back.

**Comment by felix-johnny** [comment]
@seemakumar8 Apologies for the delay, but I couldn't find a caffe model for that example.
