### ISSUE TITLE
Incorrect title in some CMSIS-DSP file headers

### ISSUE THREAD

**Issue by stephanosio** [ARM-software/CMSIS_5#890]
Nits: Found some incorrect "titles" in the source file headers

https://github.com/ARM-software/CMSIS_5/blob/a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f32.c#L3

https://github.com/ARM-software/CMSIS_5/blob/a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_f64.c#L3

https://github.com/ARM-software/CMSIS_5/blob/a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f32.c#L3

https://github.com/ARM-software/CMSIS_5/blob/a65b7c9a3e6502127fdb80eb288d8cbdf251a6f4/CMSIS/DSP/Source/TransformFunctions/arm_rfft_fast_init_f64.c#L3

**Comment by christophe0606** [comment]
Thank you. I'll correct this.

**Comment by christophe0606** [comment]
Corrected in latest commits.
