### ISSUE TITLE
RTOSv2 Flags new library version with osFlagsNoClear

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#91]
I have tried my test programs using Thread Flags. With the new version of library, the programs does not longer work.

I have changed the wait function from
`osThreadFlagsWait(TFLAG_THR1_FLAG2|TFLAG_THR1_FLAG3, 
                      osFlagsWaitAll|osFlagsAutoClear, osWaitForever);`
to
`osThreadFlagsWait(TFLAG_THR1_FLAG2|TFLAG_THR1_FLAG3, 
                      osFlagsWaitAll, osWaitForever);`

does work for a certain time, then nothing happen (no error)
[03-ThreadFlag.zip](https://github.com/ARM-software/CMSIS_5/files/526222/03-ThreadFlag.zip)

**Comment by RobertRostohar** [comment]
Thanks for the reproducer which helped to quickly identify and fix the problem (introduced with recent modifications).

Source code has been updated and rebuilt libraries will follow shortly.
