### ISSUE TITLE
【CMSIS-DAP】 I have a question about CMSIS-DAP DAP_ProcessCommand.

### ISSUE THREAD

**Issue by balanceTWK** [ARM-software/CMSIS_5#937]
![DAP_ProcessCommand](https://user-images.githubusercontent.com/30776697/83389467-dce41580-a422-11ea-9b60-45f02b7609a5.png)

![CMSIS-DAP-MDK](https://user-images.githubusercontent.com/30776697/83389808-55e36d00-a423-11ea-81a0-d60c2cbf32d4.png)

The MDK did not process the subsequent operations are it because the DAP_Info function did not return the correct value ?

**Comment by balanceTWK** [comment]
I'm currently trying to port cmsis-dap to the USB protocol stack of rt-thread (RTOS).

**Comment by JonatanAntoni** [comment]
Hi @balanceTWK,

Its hard to tell you details without knowing your environment. 
Did you take a close look into the documentation at https://arm-software.github.io/CMSIS_5/DAP?

Do you have a test environment with a functional DAP implementation for?

Cheers,
Jonatan

**Comment by balanceTWK** [comment]
> Hi @balanceTWK,
> 
> Its hard to tell you details without knowing your environment.
> Did you take a close look into the documentation at https://arm-software.github.io/CMSIS_5/DAP?
> 
> Do you have a test environment with a functional DAP implementation for?
> 
> Cheers,
> Jonatan

@JonatanAntoni  Thank you very much for your reminding.

I have been looking at the official documentation, but today I found out that cmsis-dap provides a Validation\MDK5\test.bat to test the DAP function. 囧rz。 I have solved my previous problem and now I am stuck in SWD/JTAG Communication Failure。

![image](https://user-images.githubusercontent.com/30776697/83501308-82b28580-a4f2-11ea-9a08-6df7b2b80941.png)

![DAP_TEST](https://user-images.githubusercontent.com/30776697/83502836-c60df380-a4f4-11ea-944a-cf21ef776e09.png)

![DAP_TEST0](https://user-images.githubusercontent.com/30776697/83504554-3453b580-a4f7-11ea-9fd1-358a9c72b6ef.png)

![image](https://user-images.githubusercontent.com/30776697/83503528-c5299180-a4f5-11ea-946b-f95754f40900.png)

Does this mean there is a problem with my SWD GPIO simulation?Or something else?

**Comment by JonatanAntoni** [comment]
Hi @balanceTWK,

well, going to analyse the actual serial wire communication between your DAP controller and the target processor can hardly be done on this forum.

Let me reraise one of my questions: Do you have a running DAP firmware for your environment?

I'd rather avoid changing multiple aspects at once. If its your primary interest to port CMSIS-DAP to another USB-stack implementation, I recommend to use a board which already has running CMSIS-DAP support. This would make it easier to compare the "original debugger firmware" with your modified one.

The serial wire communication is often realized using bit-banging the GPIO pins. This requires a very exact timing in your software. Therefore the DAP examples contain some macros for accurate busy waiting by doing a pre-calculated number of NOPs. Please be aware that the overall timing is very sensitive to compiler optimization. The example should work with Arm Compiler on highest optimization, only. If the timing is not exact, you might get it basically working when selecting a lower speed in MDK.

Cheers,
Jonatan

**Comment by balanceTWK** [comment]
@JonatanAntoni  Thank you very much. I will solve the problem according to your way of thinking.😉
