### ISSUE TITLE
[Build]  error: bad value (cortex-m7) for -mtune= switch

### ISSUE THREAD

**Issue by KyuhwanYeon** [ARM-software/CMSIS_5#956]
Hello. I'm trying to build CMSIS/DSP

I followed [ReadMe](https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/DSP) in CMSIS/DSP

But  I failed to build it

OS: Ubuntu 16.04
Tool chain: GNU Arm Embedded Toolchain, Version 9-2019-q4-major

When I tried terminal
`cmake -DROOT="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5"   -DCMAKE_PREFIX_PATH="/home/kyuhwanyeon/gcc-arm-none-eabi-9-2019-q4-major/bin"   -DCMAKE_TOOLCHAIN_FILE="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5/CMSIS/DSP/armac6.cmake"   -DARM_CPU="cortex-m7"   -G "Unix Makefiles" ..`

The result

![image](https://user-images.githubusercontent.com/29419709/86090884-e2964f00-bae5-11ea-88b1-80693693c745.png)

Could you explain what happend, and how can i solve this error?
Thank you

**Comment by JonatanAntoni** [comment]
Hi @KyuhwanYeon,

I am not an expert in the CMake area. But it looks like in your environment the wrong compiler command is picked up, i.e. /usr/bin/cc probably doesn't point to the desired GNU Arm Embedded Toolchain. Can you please double check that?

Perhaps @christophe0606 can give you more details about CMake stuff.

Cheers,
Jonatan

**Comment by christophe0606** [comment]
Hi @KyuhwanYeon,

For CMAKE_PREFIX_PATH, there should not be a bin at the end of the path

And since you are building with gcc, then the toolchain CMAKE_TOOLCHAIN_FILE should not point to armac6.cmake but to gcc.cmake

**Comment by christophe0606** [comment]
I advise if you change those settings to clean your build folder before trying again : CMakeCache.txt, CMakeFiles ...
Otherwise you may have remaining issues

**Comment by KyuhwanYeon** [comment]
Yeap. Now, I removed build folder and change CMAKE_PREFIX_PATH and CMAKE_TOOLCHAIN_FILE by your comment.

But result show another error
```
kyuhwanyeon@kyuhwanyeon-MS-7B17:~/workspace/2000_CMSIS_ws/BuildCMSISOnly/build$ cmake -DROOT="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5"   -DCMAKE_PREFIX_PATH="/home/kyuhwanyeon/gcc-arm-none-eabi-9-2020-q2-update/"   -DCMAKE_TOOLCHAIN_FILE="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5/CMSIS/DSP/gcc.cmake"   -DARM_CPU="cortex-m7"   -G "Unix Makefiles" .. 
CMake Error at /home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5/CMSIS/DSP/gcc.cmake:61 (add_link_options):
  Unknown CMake command "add_link_options".
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:4 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

```

my cmake version is 11. and I also updated build-essentials.

**Comment by christophe0606** [comment]
@KyuhwanYeon I am using cmake 3.14.3
I know there are issues with too recent ones. I don't know if 3.11 is ok. But it looks like it may be too old : "add_link_options" is not a recognized command.

Try with the 3.14.

**Comment by TTornblom** [comment]
Looks like you don’t have a working “make” in your path.

Thomas

Thomas Törnblom, Product Engineer
IAR Systems AB
Box 23051, Strandbodgatan 1<x-apple-data-detectors://6/1>
SE-750 23 Uppsala, SWEDEN<x-apple-data-detectors://6/1>
Mobile: +46 76 180 17 80<tel:+46%2076%20180%2017%2080> Fax: +46 18 16 78 01<tel:+46%2018%2016%2078%2001>
E-mail: thomas.tornblom@iar.com<mailto:thomas.tornblom@iar.com> Website: www.iar.com<http://www.iar.com/>
Twitter: www.twitter.com/iarsystems<http://www.twitter.com/iarsystems>

1 juli 2020 kl. 02:58 skrev KyuhwanYeon <notifications@github.com>:

﻿

Yeap. Now, I removed build folder and change CMAKE_PREFIX_PATH and CMAKE_TOOLCHAIN_FILE by your comment.

But result show another error

kyuhwanyeon@kyuhwanyeon-MS-7B17:~/workspace/2000_CMSIS_ws/BuildCMSISOnly/build$ cmake -DROOT="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5"   -DCMAKE_PREFIX_PATH="/home/kyuhwanyeon/gcc-arm-none-eabi-9-2020-q2-update/"   -DCMAKE_TOOLCHAIN_FILE="/home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5/CMSIS/DSP/gcc.cmake"   -DARM_CPU="cortex-m7"   -G "Unix Makefiles" ..
CMake Error at /home/kyuhwanyeon/workspace/2000_CMSIS_ws/CMSIS_5/CMSIS/DSP/gcc.cmake:61 (add_link_options):
  Unknown CMake command "add_link_options".
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:4 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!



my cmake version is 11. and I also updated build-essentials.

**Comment by KyuhwanYeon** [comment]
Thank you for your valuable comments. Now, I success to build
The problem was CMakeversion as @christophe0606  said.
I change the CMake version as 3.17. Then, I can build.

But I suggest modifying the CMakeList.txt

It said
cmake_minimum_required (VERSION 3.6)

But, It is not working as i mentioned in this issue.
I think minimum version should be changed as 3.14 

Thank you

**Comment by christophe0606** [comment]
@KyuhwanYeon  I'll update the version number in cmake_minimum_required  in a future commit.
