### ISSUE TITLE
DSP Lib Compile Script batch file has no mkdir of archive dir

### ISSUE THREAD

**Issue by ckYoung666** [ARM-software/CMSIS_5#975]
You should add a mkdir ..\..\Lib\ARM before build start in CMSIS/DSP/Projects/arm_cortexM_math_Build.bat 
otherwise after all build done. if no Lib\ARM was created,all lib will be deleted.
or you can upload Lib\ARM Lib\GCC directory

**Comment by christophe0606** [comment]
Pre-built libraries are no more included with CMSIS-DSP.
