### ISSUE TITLE
RTOS2 Debug

### ISSUE THREAD

**Issue by eugene345** [ARM-software/CMSIS_5#99]
I found that new feature was added recently. But after I choose Debug variant for Keil RTX5 component in   the "manage run-time environment" window I see that new component required, which is not available from current packs:

![image](https://cloud.githubusercontent.com/assets/14873555/19768243/56f2cdb4-9c5f-11e6-8fbe-964d98d03e92.png)

And another question. Do you plan to integrate CMSIS 5 with the "Event viewer" and "System and thread viewer"? I use "Component viewer" now, but it is not so informative as tools above.

**Comment by RobertRostohar** [comment]
The required dependency on Event Recorder is removed now (it will be optional to use it - not yet supported).

"Component Viewer" is a replacement for "System and thread viewer" and provides much more information.

"Event Viewer" is being replaced with "Event Recorder" which will also provide more events (not just thread switches).

**Comment by eugene345** [comment]
Is there any option to show in the Component viewer information about dynamically allocated objects?

I can see the new component - Event recorder. But it uses CMSIS-DAP.  Does it mean that high-grade debuggers (such as ULINKpro) become useless when debugging RTOS applications? Because there is no CMSIS-DAP driver for it. 
And also CMSIS-DAP doesn't support ETM. So, if driver appears, adapter will loose access to ETM.

**Comment by RobertRostohar** [comment]
> Is there any option to show in the Component viewer information about dynamically allocated objects?

Yes, dynamically allocated objects should be shown.

> Event recorder. But it uses CMSIS-DAP

It does not use CMSIS-DAP but Debug Access Port (DAP) and will work with any debugger connected through DAP (JTAG/SWD). There is no need for any CMSIS-DAP driver or any other adaptation of existing debuggers..

**Comment by eugene345** [comment]
Thanks for the explanation.
Does RTOS2 have event annotations to work with Event recorder now?

**Comment by jankap** [comment]
> Thanks for the explanation.
> Does RTOS2 have event annotations to work with Event recorder now?

That is interesting for me too, because with uvision 5.22, RTX5 and CMSIS-RTOS2 the event recorder remains empty (except my own test messages) and the event viewer (which is very important for us, because of the good overview in time) does not display the threads, only exceptions. The latter makes sense because I couldn't find any source code writing to ITM Port 31 anymore (HAL_CM.c has done this before). Is there a timeline when these features are expected to work again?

Thank you!

**Comment by ReinhardKeil** [comment]
released as part of CMSIS 5.0.1
